#!/bin/bash

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

# Evaluation benchmarks.
TASKS=("videomme" "mvbench" "longvideobench_val_v" "egoschema")

# Pretrained model path.
PRETRAINED="lmms-lab/LLaVA-Video-7B-Qwen2"

# ! FlashVid arguments.
RETENTION_RATIOS=(0.10 0.15 0.20 0.25)
## Dyseg (fixed)
DO_SEGMENT=True
MIN_SEGMENT_NUM=8
COMPLEMENTARY_SEGMENT=True
## ADTS and TSTM (fixed)
TOKEN_SELECTION_METHOD=attn_div_v2
TEMPORAL_THRESHOLD=0.8
ALPHA=0.7
COMPRESSION_VARIANT=${COMPRESSION_VARIANT:-flashvid}
CERTV3_BUDGET_USES_EXPANSION=${CERTV3_BUDGET_USES_EXPANSION:-True}
CERTV3_QUERY_ATOMS=${CERTV3_QUERY_ATOMS:-8}
CERTV3_TEMPORAL_BINS=${CERTV3_TEMPORAL_BINS:-12}
CERTV3_SPATIAL_BINS=${CERTV3_SPATIAL_BINS:-3}
CERTV3_CANDIDATE_MULTIPLIER=${CERTV3_CANDIDATE_MULTIPLIER:-2.5}
CERTV3_QUERY_WEIGHT=${CERTV3_QUERY_WEIGHT:-0.18}
CERTV3_TRACK_THRESHOLD=${CERTV3_TRACK_THRESHOLD:-0.82}
CERTV3_SPATIAL_PENALTY=${CERTV3_SPATIAL_PENALTY:-0.08}
CERTV3_METRIC_DIM=${CERTV3_METRIC_DIM:-96}
CERTV3_FRAME_COVERAGE_RATIO=${CERTV3_FRAME_COVERAGE_RATIO:-1.0}
CERTV3_CELL_COVERAGE_RATIO=${CERTV3_CELL_COVERAGE_RATIO:-0.50}
CERTV3_QUERY_THRESHOLD=${CERTV3_QUERY_THRESHOLD:-0.10}
CERTV3_QUERY_PER_ATOM=${CERTV3_QUERY_PER_ATOM:-1}
CERTV3_STRUCTURAL_WEIGHT=${CERTV3_STRUCTURAL_WEIGHT:-0.32}
CERTV3_WHITENING_STRENGTH=${CERTV3_WHITENING_STRENGTH:-0.50}
CERTV3_QUALITY_FLOOR=${CERTV3_QUALITY_FLOOR:-0.15}
CERTV3_RIDGE=${CERTV3_RIDGE:-0.50}
CERTV3_SWAP_STEPS=${CERTV3_SWAP_STEPS:-6}
CERTV3_SWAP_POOL=${CERTV3_SWAP_POOL:-24}
CERTV3_SWAP_MARGIN=${CERTV3_SWAP_MARGIN:-0.0001}
CERTV3_FUSION_ALPHA=${CERTV3_FUSION_ALPHA:-0.12}
CERTV3_ASSIGNMENT_TEMPERATURE=${CERTV3_ASSIGNMENT_TEMPERATURE:-0.07}
FAITH_BUDGET_USES_EXPANSION=${FAITH_BUDGET_USES_EXPANSION:-True}
FAITH_MASS_STRENGTH=${FAITH_MASS_STRENGTH:-1.0}
FAITH_VARIANCE_STRENGTH=${FAITH_VARIANCE_STRENGTH:-0.50}
FAITH_MERGE_ALPHA=${FAITH_MERGE_ALPHA:-1.0}
FAITH_TEMPORAL_RADIUS=${FAITH_TEMPORAL_RADIUS:-1}
FAITH_SPATIAL_RADIUS=${FAITH_SPATIAL_RADIUS:-0.75}
FAITH_COMPONENT_BONUS=${FAITH_COMPONENT_BONUS:-0.08}
FAITH_TEMPORAL_PENALTY=${FAITH_TEMPORAL_PENALTY:-0.04}
FAITH_SPATIAL_PENALTY=${FAITH_SPATIAL_PENALTY:-0.04}
FAITH_ASSIGNMENT_TOPK=${FAITH_ASSIGNMENT_TOPK:-2}
FAITH_ASSIGNMENT_TEMPERATURE=${FAITH_ASSIGNMENT_TEMPERATURE:-0.07}
FAITH_MAX_LOG_BIAS=${FAITH_MAX_LOG_BIAS:-20.0}
FAITH_ATTENTION_STRICT=${FAITH_ATTENTION_STRICT:-True}
FAITH_DEBUG=${FAITH_DEBUG:-False}
## Inner-LLM Pruning (fixed)
EXPANSION=1.25
PRUNING_LAYER=20
LLM_RETENTION_RATIO=0.3

BASE_FLASHVID_ARGS="enable_flashvid=True,expansion=$EXPANSION,do_segment=$DO_SEGMENT,min_segment_num=$MIN_SEGMENT_NUM,complementary_segment=$COMPLEMENTARY_SEGMENT,token_selection_method=$TOKEN_SELECTION_METHOD,alpha=$ALPHA,temporal_threshold=$TEMPORAL_THRESHOLD,compression_variant=$COMPRESSION_VARIANT,certv3_budget_uses_expansion=$CERTV3_BUDGET_USES_EXPANSION,certv3_query_atoms=$CERTV3_QUERY_ATOMS,certv3_temporal_bins=$CERTV3_TEMPORAL_BINS,certv3_spatial_bins=$CERTV3_SPATIAL_BINS,certv3_candidate_multiplier=$CERTV3_CANDIDATE_MULTIPLIER,certv3_query_weight=$CERTV3_QUERY_WEIGHT,certv3_track_threshold=$CERTV3_TRACK_THRESHOLD,certv3_spatial_penalty=$CERTV3_SPATIAL_PENALTY,certv3_metric_dim=$CERTV3_METRIC_DIM,certv3_frame_coverage_ratio=$CERTV3_FRAME_COVERAGE_RATIO,certv3_cell_coverage_ratio=$CERTV3_CELL_COVERAGE_RATIO,certv3_query_threshold=$CERTV3_QUERY_THRESHOLD,certv3_query_per_atom=$CERTV3_QUERY_PER_ATOM,certv3_structural_weight=$CERTV3_STRUCTURAL_WEIGHT,certv3_whitening_strength=$CERTV3_WHITENING_STRENGTH,certv3_quality_floor=$CERTV3_QUALITY_FLOOR,certv3_ridge=$CERTV3_RIDGE,certv3_swap_steps=$CERTV3_SWAP_STEPS,certv3_swap_pool=$CERTV3_SWAP_POOL,certv3_swap_margin=$CERTV3_SWAP_MARGIN,certv3_fusion_alpha=$CERTV3_FUSION_ALPHA,certv3_assignment_temperature=$CERTV3_ASSIGNMENT_TEMPERATURE,faith_budget_uses_expansion=$FAITH_BUDGET_USES_EXPANSION,faith_mass_strength=$FAITH_MASS_STRENGTH,faith_variance_strength=$FAITH_VARIANCE_STRENGTH,faith_merge_alpha=$FAITH_MERGE_ALPHA,faith_temporal_radius=$FAITH_TEMPORAL_RADIUS,faith_spatial_radius=$FAITH_SPATIAL_RADIUS,faith_component_bonus=$FAITH_COMPONENT_BONUS,faith_temporal_penalty=$FAITH_TEMPORAL_PENALTY,faith_spatial_penalty=$FAITH_SPATIAL_PENALTY,faith_assignment_topk=$FAITH_ASSIGNMENT_TOPK,faith_assignment_temperature=$FAITH_ASSIGNMENT_TEMPERATURE,faith_max_log_bias=$FAITH_MAX_LOG_BIAS,faith_attention_strict=$FAITH_ATTENTION_STRICT,faith_debug=$FAITH_DEBUG,pruning_layer=$PRUNING_LAYER,llm_retention_ratio=$LLM_RETENTION_RATIO"

# Model arguments.
MAX_FRAMES_NUM=64
CONV_TEMPLATE=qwen_1_5
FORCE_SAMPLE=True
ADD_TIME_INSTRUCTION=False
MM_SPATIAL_POOL_MODE=average # * Different from LLaVA-OneVision
MM_NEWLINE_POSITION=frame # Add newline token after each frame.
ATTN_IMPLEMENTATION=flash_attention_2
BASE_MODEL_ARGS="pretrained=$PRETRAINED,conv_template=$CONV_TEMPLATE,mm_spatial_pool_mode=$MM_SPATIAL_POOL_MODE,mm_newline_position=$MM_NEWLINE_POSITION,max_frames_num=$MAX_FRAMES_NUM,attn_implementation=$ATTN_IMPLEMENTATION,force_sample=$FORCE_SAMPLE,add_time_instruction=$ADD_TIME_INSTRUCTION"


for retention_ratio in "${RETENTION_RATIOS[@]}"; do
    echo "Running with retention_ratio=${retention_ratio}"
    MODEL_ARGS="$BASE_MODEL_ARGS,$BASE_FLASHVID_ARGS,retention_ratio=${retention_ratio}"
    for task in "${TASKS[@]}"; do
        echo "Evaluating task: $task"
        accelerate launch \
            --main_process_port 18888 \
            --num_processes 8 \
            -m lmms_eval \
            --model llava_vid \
            --model_args $MODEL_ARGS \
            --tasks $task \
            --batch_size 1 \
            --log_samples \
            --log_samples_suffix "llava_vid" \
            --output_path ./logs/flashvid
    done
    echo "Finished running with retention_ratio=${retention_ratio}"
done
