#!/usr/bin/env bash
set -euo pipefail

# LLaVA-OneVision lmms-eval runner. Defaults reproduce the FlashVID table
# settings while allowing one method, task, or retention rate to be selected.
cd "$(dirname "$0")/.."

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTHONPATH="$PWD:$PWD/lmms-eval:${PYTHONPATH:-}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export DECORD_EOF_RETRY_MAX="${DECORD_EOF_RETRY_MAX:-20480}"

ACCELERATE="${ACCELERATE:-accelerate}"
PYTHON_BIN="${PYTHON_BIN:-python}"
MAIN_PROCESS_PORT="${MAIN_PROCESS_PORT:-18888}"
NUM_PROCESSES="${NUM_PROCESSES:-1}"

PRETRAINED="${PRETRAINED:-lmms-lab/llava-onevision-qwen2-7b-ov}"
METHODS="${METHODS:-flashvid}"
RATES="${RATES:-0.10,0.15,0.20,0.25}"
TASKS="${TASKS:-videomme,mvbench,longvideobench_val_v,egoschema}"
OUTPUT_PATH="${OUTPUT_PATH:-./logs/llava_onevision}"
LIMIT="${LIMIT:-}"
LOG_SAMPLES="${LOG_SAMPLES:-0}"
BATCH_SIZE="${BATCH_SIZE:-1}"

DO_SEGMENT="${DO_SEGMENT:-True}"
SEGMENT_THRESHOLD="${SEGMENT_THRESHOLD:-0.9}"
MIN_SEGMENT_NUM="${MIN_SEGMENT_NUM:-8}"
COMPLEMENTARY_SEGMENT="${COMPLEMENTARY_SEGMENT:-True}"
ALPHA="${ALPHA:-0.70}"
TEMPORAL_THRESHOLD="${TEMPORAL_THRESHOLD:-0.8}"
EXPANSION="${EXPANSION:-1.25}"
PRUNING_LAYER="${PRUNING_LAYER:-20}"
LLM_RETENTION_RATIO="${LLM_RETENTION_RATIO:-0.3}"

MAX_FRAMES_NUM="${MAX_FRAMES_NUM:-32}"
CONV_TEMPLATE="${CONV_TEMPLATE:-qwen_1_5}"
MM_SPATIAL_POOL_MODE="${MM_SPATIAL_POOL_MODE:-bilinear}"
ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION:-flash_attention_2}"

FLASHVID_TOKEN_SELECTION_METHOD="${FLASHVID_TOKEN_SELECTION_METHOD:-attn_div_v2}"
CERT_TOKEN_SELECTION_METHOD="${CERT_TOKEN_SELECTION_METHOD:-attn_div_stable}"
CERTV2_TOKEN_SELECTION_METHOD="${CERTV2_TOKEN_SELECTION_METHOD:-attn_div_stable}"
CERTV3_TOKEN_SELECTION_METHOD="${CERTV3_TOKEN_SELECTION_METHOD:-attn_div_stable}"
CERTV6_TOKEN_SELECTION_METHOD="${CERTV6_TOKEN_SELECTION_METHOD:-$CERTV3_TOKEN_SELECTION_METHOD}"
CERTV4_TOKEN_SELECTION_METHOD="${CERTV4_TOKEN_SELECTION_METHOD:-attn_div_stable}"
CERTV5_TOKEN_SELECTION_METHOD="${CERTV5_TOKEN_SELECTION_METHOD:-attn_div_stable}"
CERTE_TOKEN_SELECTION_METHOD="${CERTE_TOKEN_SELECTION_METHOD:-attn_div_stable}"

CERT_BUDGET_USES_EXPANSION="${CERT_BUDGET_USES_EXPANSION:-True}"
CERT_QUERY_ATOMS="${CERT_QUERY_ATOMS:-6}"
CERT_TEMPORAL_BINS="${CERT_TEMPORAL_BINS:-8}"
CERT_SPATIAL_BINS="${CERT_SPATIAL_BINS:-3}"
CERT_CANDIDATE_MULTIPLIER="${CERT_CANDIDATE_MULTIPLIER:-3.0}"
CERT_QUERY_WEIGHT="${CERT_QUERY_WEIGHT:-0.20}"
CERT_TEMPORAL_WEIGHT="${CERT_TEMPORAL_WEIGHT:-0.20}"
CERT_DETAIL_WEIGHT="${CERT_DETAIL_WEIGHT:-0.10}"
CERT_REPAIR_RATIO="${CERT_REPAIR_RATIO:-0.20}"
CERT_FUSION_ALPHA="${CERT_FUSION_ALPHA:-0.25}"
CERT_ASSIGNMENT_TEMPERATURE="${CERT_ASSIGNMENT_TEMPERATURE:-0.07}"
CERT_TRACK_THRESHOLD="${CERT_TRACK_THRESHOLD:-0.82}"
CERT_SPATIAL_PENALTY="${CERT_SPATIAL_PENALTY:-0.08}"
CERT_METRIC_DIM="${CERT_METRIC_DIM:-256}"

CERTV2_BUDGET_USES_EXPANSION="${CERTV2_BUDGET_USES_EXPANSION:-True}"
CERTV2_QUERY_ATOMS="${CERTV2_QUERY_ATOMS:-6}"
CERTV2_TEMPORAL_BINS="${CERTV2_TEMPORAL_BINS:-8}"
CERTV2_SPATIAL_BINS="${CERTV2_SPATIAL_BINS:-3}"
CERTV2_CANDIDATE_MULTIPLIER="${CERTV2_CANDIDATE_MULTIPLIER:-3.0}"
CERTV2_QUERY_WEIGHT="${CERTV2_QUERY_WEIGHT:-0.18}"
CERTV2_FRAME_FLOOR_RATIO="${CERTV2_FRAME_FLOOR_RATIO:-0.08}"
CERTV2_DIVERSITY_WEIGHT="${CERTV2_DIVERSITY_WEIGHT:-0.12}"
CERTV2_COVERAGE_WEIGHT="${CERTV2_COVERAGE_WEIGHT:-0.10}"
CERTV2_DENSITY_NEIGHBORS="${CERTV2_DENSITY_NEIGHBORS:-4}"
CERTV2_TRACK_THRESHOLD="${CERTV2_TRACK_THRESHOLD:-0.82}"
CERTV2_SPATIAL_PENALTY="${CERTV2_SPATIAL_PENALTY:-0.08}"
CERTV2_METRIC_DIM="${CERTV2_METRIC_DIM:-256}"
CERTV2_REPAIR_RATIO="${CERTV2_REPAIR_RATIO:-0.05}"
CERTV2_REPAIR_RATIO_HIGH="${CERTV2_REPAIR_RATIO_HIGH:-0.13}"
CERTV2_ROUTER_STRENGTH="${CERTV2_ROUTER_STRENGTH:-0.65}"
CERTV2_PROTECT_RATIO="${CERTV2_PROTECT_RATIO:-0.30}"
CERTV2_SWAP_MARGIN="${CERTV2_SWAP_MARGIN:-0.02}"
CERTV2_FUSION_ALPHA="${CERTV2_FUSION_ALPHA:-0.25}"
CERTV2_REPAIR_FUSION_ALPHA="${CERTV2_REPAIR_FUSION_ALPHA:-0.08}"
CERTV2_ASSIGNMENT_TEMPERATURE="${CERTV2_ASSIGNMENT_TEMPERATURE:-0.07}"

CERTV3_BUDGET_USES_EXPANSION="${CERTV3_BUDGET_USES_EXPANSION:-True}"
CERTV3_QUERY_ATOMS="${CERTV3_QUERY_ATOMS:-8}"
CERTV3_TEMPORAL_BINS="${CERTV3_TEMPORAL_BINS:-12}"
CERTV3_SPATIAL_BINS="${CERTV3_SPATIAL_BINS:-3}"
CERTV3_CANDIDATE_MULTIPLIER="${CERTV3_CANDIDATE_MULTIPLIER:-2.5}"
CERTV3_QUERY_WEIGHT="${CERTV3_QUERY_WEIGHT:-0.18}"
CERTV3_TRACK_THRESHOLD="${CERTV3_TRACK_THRESHOLD:-0.82}"
CERTV3_SPATIAL_PENALTY="${CERTV3_SPATIAL_PENALTY:-0.08}"
CERTV3_METRIC_DIM="${CERTV3_METRIC_DIM:-96}"
CERTV3_FRAME_COVERAGE_RATIO="${CERTV3_FRAME_COVERAGE_RATIO:-1.0}"
CERTV3_CELL_COVERAGE_RATIO="${CERTV3_CELL_COVERAGE_RATIO:-0.50}"
CERTV3_QUERY_THRESHOLD="${CERTV3_QUERY_THRESHOLD:-0.10}"
CERTV3_QUERY_PER_ATOM="${CERTV3_QUERY_PER_ATOM:-1}"
CERTV3_STRUCTURAL_WEIGHT="${CERTV3_STRUCTURAL_WEIGHT:-0.32}"
CERTV3_WHITENING_STRENGTH="${CERTV3_WHITENING_STRENGTH:-0.50}"
CERTV3_QUALITY_FLOOR="${CERTV3_QUALITY_FLOOR:-0.15}"
CERTV3_RIDGE="${CERTV3_RIDGE:-0.50}"
CERTV3_SWAP_STEPS="${CERTV3_SWAP_STEPS:-6}"
CERTV3_SWAP_POOL="${CERTV3_SWAP_POOL:-24}"
CERTV3_SWAP_MARGIN="${CERTV3_SWAP_MARGIN:-0.0001}"
CERTV3_FUSION_ALPHA="${CERTV3_FUSION_ALPHA:-0.12}"
CERTV3_ASSIGNMENT_TEMPERATURE="${CERTV3_ASSIGNMENT_TEMPERATURE:-0.07}"

CERTV6_SCENE_TEMPORAL="${CERTV6_SCENE_TEMPORAL:-True}"
CERTV6_GATE_ENABLED="${CERTV6_GATE_ENABLED:-True}"
CERTV6_CONTINUITY_LOW="${CERTV6_CONTINUITY_LOW:-0.55}"
CERTV6_CONTINUITY_HIGH="${CERTV6_CONTINUITY_HIGH:-0.80}"
CERTV6_QUERY_PER_ATOM_MAX="${CERTV6_QUERY_PER_ATOM_MAX:-3}"

CERTV7_TOKEN_SELECTION_METHOD="${CERTV7_TOKEN_SELECTION_METHOD:-$CERTV3_TOKEN_SELECTION_METHOD}"
CERTV7_MIN_DURATION_SECONDS="${CERTV7_MIN_DURATION_SECONDS:-120.0}"
CERTV7_TRANSPORT_SPATIAL_BINS="${CERTV7_TRANSPORT_SPATIAL_BINS:-4}"
CERTV7_TRANSPORT_EPSILON="${CERTV7_TRANSPORT_EPSILON:-0.08}"
CERTV7_TRANSPORT_STEPS="${CERTV7_TRANSPORT_STEPS:-8}"
CERTV7_TRANSPORT_SPATIAL_WEIGHT="${CERTV7_TRANSPORT_SPATIAL_WEIGHT:-0.20}"
CERTV7_FRAME_FLOOR_RATIO="${CERTV7_FRAME_FLOOR_RATIO:-1.0}"
CERTV7_FRAME_CAP_RATIO="${CERTV7_FRAME_CAP_RATIO:-1.0}"
CERTV7_BUDGET_TEMPERATURE="${CERTV7_BUDGET_TEMPERATURE:-0.50}"
CERTV7_UNIQUENESS_WEIGHT="${CERTV7_UNIQUENESS_WEIGHT:-0.25}"
CERTV7_TRANSPORT_WEIGHT="${CERTV7_TRANSPORT_WEIGHT:-0.35}"
CERTV7_EVENT_WEIGHT="${CERTV7_EVENT_WEIGHT:-0.20}"
CERTV7_QUERY_WEIGHT="${CERTV7_QUERY_WEIGHT:-0.20}"
CERTV7_BUDGET_ROUNDING="${CERTV7_BUDGET_ROUNDING:-per_frame_ceil}"
CERTV7_V3_CERTIFICATE_RATIO="${CERTV7_V3_CERTIFICATE_RATIO:-0.05}"
CERTV7_RELAY_RATIO="${CERTV7_RELAY_RATIO:-0.25}"
CERTV7_RELAY_QUERY_SHARE="${CERTV7_RELAY_QUERY_SHARE:-0.25}"
CERTV7_TRANSITION_RELAY_SHARE="${CERTV7_TRANSITION_RELAY_SHARE:-0.45}"
CERTV7_QUERY_PEAKS_PER_ATOM="${CERTV7_QUERY_PEAKS_PER_ATOM:-2}"
CERTV7_QUERY_MIN_FRAME_GAP="${CERTV7_QUERY_MIN_FRAME_GAP:-3}"
CERTV7_QUERY_PEAK_THRESHOLD="${CERTV7_QUERY_PEAK_THRESHOLD:-0.70}"
CERTV7_QUERY_CONTEXT_RADIUS="${CERTV7_QUERY_CONTEXT_RADIUS:-1}"
CERTV7_TRANSITION_PAIRS_PER_BOUNDARY="${CERTV7_TRANSITION_PAIRS_PER_BOUNDARY:-2}"
CERTV7_TRANSITION_MIN_SIMILARITY="${CERTV7_TRANSITION_MIN_SIMILARITY:-0.30}"
CERTV7_TRAJECTORY_MIN_SPAN="${CERTV7_TRAJECTORY_MIN_SPAN:-3}"
CERTV7_TRAJECTORY_POINTS="${CERTV7_TRAJECTORY_POINTS:-3}"
CERTV7_FACILITY_QUALITY_MIX="${CERTV7_FACILITY_QUALITY_MIX:-0.18}"
CERTV7_MIN_REALLOCATION_RATIO="${CERTV7_MIN_REALLOCATION_RATIO:-0.02}"
CERTV7_D_EFFICIENCY_FLOOR="${CERTV7_D_EFFICIENCY_FLOOR:-0.80}"
CERTV7_ASSIGNMENT_TOPK="${CERTV7_ASSIGNMENT_TOPK:-2}"
CERTV7_ASSIGNMENT_TEMPERATURE="${CERTV7_ASSIGNMENT_TEMPERATURE:-0.07}"
CERTV7_CROSS_FRAME_COST_QUANTILE="${CERTV7_CROSS_FRAME_COST_QUANTILE:-0.45}"
CERTV7_CROSS_FRAME_SIMILARITY="${CERTV7_CROSS_FRAME_SIMILARITY:-0.82}"
CERTV7_CROSS_FRAME_MAX_SECONDS="${CERTV7_CROSS_FRAME_MAX_SECONDS:-12.0}"
CERTV7_COMPONENT_BONUS="${CERTV7_COMPONENT_BONUS:-0.08}"
CERTV7_DESIGN_PROTECT_RATIO="${CERTV7_DESIGN_PROTECT_RATIO:-0.15}"
CERTV7_LONG_FUSION_ALPHA="${CERTV7_LONG_FUSION_ALPHA:-0.04}"
CERTV7_DEBUG="${CERTV7_DEBUG:-False}"

CERTV8_TOKEN_SELECTION_METHOD="${CERTV8_TOKEN_SELECTION_METHOD:-$CERTV3_TOKEN_SELECTION_METHOD}"
CERTV8_ENABLED="${CERTV8_ENABLED:-True}"
CERTV8_INTENT_ROUTER="${CERTV8_INTENT_ROUTER:-True}"
CERTV8_INTENT_STRENGTH="${CERTV8_INTENT_STRENGTH:-0.75}"
CERTV8_MIN_HORIZON_GAP_SECONDS="${CERTV8_MIN_HORIZON_GAP_SECONDS:-4.0}"
CERTV8_MIN_DEFICIT="${CERTV8_MIN_DEFICIT:-0.04}"
CERTV8_FRAME_FLOOR_RATIO="${CERTV8_FRAME_FLOOR_RATIO:-0.45}"
CERTV8_FRAME_CAP_RATIO="${CERTV8_FRAME_CAP_RATIO:-2.00}"
CERTV8_MAX_SWAP_RATIO="${CERTV8_MAX_SWAP_RATIO:-0.30}"
CERTV8_CONCENTRATION_PRESERVE_RATIO="${CERTV8_CONCENTRATION_PRESERVE_RATIO:-0.55}"
CERTV8_QUERY_PEAK_COUNT="${CERTV8_QUERY_PEAK_COUNT:-2}"
CERTV8_QUERY_PEAK_SEPARATION="${CERTV8_QUERY_PEAK_SEPARATION:-2}"
CERTV8_QUERY_WEIGHT="${CERTV8_QUERY_WEIGHT:-0.30}"
CERTV8_EVENT_WEIGHT="${CERTV8_EVENT_WEIGHT:-0.25}"
CERTV8_BALANCE_WEIGHT="${CERTV8_BALANCE_WEIGHT:-0.30}"
CERTV8_DESIGN_PROTECT_RATIO="${CERTV8_DESIGN_PROTECT_RATIO:-0.08}"
CERTV8_QUERY_PROTECT_RATIO="${CERTV8_QUERY_PROTECT_RATIO:-0.05}"
CERTV8_D_EFFICIENCY_FLOOR="${CERTV8_D_EFFICIENCY_FLOOR:-0.95}"
CERTV8_MIN_OBJECTIVE_GAIN="${CERTV8_MIN_OBJECTIVE_GAIN:-0.001}"
CERTV8_CROSS_FRAME_SIMILARITY="${CERTV8_CROSS_FRAME_SIMILARITY:-0.88}"
CERTV8_CROSS_FRAME_MAX_SECONDS="${CERTV8_CROSS_FRAME_MAX_SECONDS:-8.0}"
CERTV8_STRATIFIED_ENABLED="${CERTV8_STRATIFIED_ENABLED:-True}"
CERTV8_STRATIFIED_TEMPORAL_STRENGTH="${CERTV8_STRATIFIED_TEMPORAL_STRENGTH:-0.60}"
CERTV8_STRATIFIED_RETRIEVAL_STRENGTH="${CERTV8_STRATIFIED_RETRIEVAL_STRENGTH:-0.40}"
CERTV8_STRATIFIED_GENERIC_STRENGTH="${CERTV8_STRATIFIED_GENERIC_STRENGTH:-0.0}"
CERTV8_STRATIFIED_MIN_QUESTION_WORDS="${CERTV8_STRATIFIED_MIN_QUESTION_WORDS:-12}"
CERTV8_STRATIFIED_V3_KEEP_RATIO="${CERTV8_STRATIFIED_V3_KEEP_RATIO:-0.50}"
CERTV8_STRATIFIED_MAX_DURATION_SECONDS="${CERTV8_STRATIFIED_MAX_DURATION_SECONDS:-1200.0}"
CERTV8_STRATIFIED_D_EFFICIENCY_FLOOR="${CERTV8_STRATIFIED_D_EFFICIENCY_FLOOR:-0.82}"
CERTV8_STRATIFIED_QUERY_TOLERANCE="${CERTV8_STRATIFIED_QUERY_TOLERANCE:-0.01}"
CERTV8_DEBUG="${CERTV8_DEBUG:-True}"
CERTV8_DIAGNOSTICS_DETAIL="${CERTV8_DIAGNOSTICS_DETAIL:-summary}"
FLASHVID_DIAGNOSTICS_DETAIL="${FLASHVID_DIAGNOSTICS_DETAIL:-summary}"

CERTHR_TOKEN_SELECTION_METHOD="${CERTHR_TOKEN_SELECTION_METHOD:-$CERTV3_TOKEN_SELECTION_METHOD}"
CERTHR_HORIZON_GAP_SECONDS="${CERTHR_HORIZON_GAP_SECONDS:-4.0}"
CERTHR_CHUNK_MAX_SECONDS="${CERTHR_CHUNK_MAX_SECONDS:-60.0}"
CERTHR_CHUNK_MAX_UNITS="${CERTHR_CHUNK_MAX_UNITS:-4}"
CERTHR_SEMANTIC_QUANTILE="${CERTHR_SEMANTIC_QUANTILE:-0.85}"
CERTHR_SEMANTIC_FLOOR="${CERTHR_SEMANTIC_FLOOR:-0.10}"
CERTHR_COVERAGE_FLOOR="${CERTHR_COVERAGE_FLOOR:-0.70}"
CERTHR_DEFICIT_THRESHOLD="${CERTHR_DEFICIT_THRESHOLD:-0.05}"
CERTHR_QUERY_PEAK_QUANTILE="${CERTHR_QUERY_PEAK_QUANTILE:-0.90}"
CERTHR_QUERY_PEAK_FLOOR="${CERTHR_QUERY_PEAK_FLOOR:-0.75}"
CERTHR_MAX_SWAP_RATIO="${CERTHR_MAX_SWAP_RATIO:-0.05}"
CERTHR_D_EFFICIENCY_FLOOR="${CERTHR_D_EFFICIENCY_FLOOR:-0.995}"
CERTHR_ADD_POOL="${CERTHR_ADD_POOL:-32}"
CERTHR_REMOVE_POOL="${CERTHR_REMOVE_POOL:-24}"
CERTHR_DEBUG="${CERTHR_DEBUG:-False}"

CERTLH_TOKEN_SELECTION_METHOD="${CERTLH_TOKEN_SELECTION_METHOD:-$CERTV3_TOKEN_SELECTION_METHOD}"
CERTLH_MIN_DURATION_SECONDS="${CERTLH_MIN_DURATION_SECONDS:-120.0}"
CERTLH_HORIZON_GAP_SECONDS="${CERTLH_HORIZON_GAP_SECONDS:-4.0}"
CERTLH_GATE_THRESHOLD="${CERTLH_GATE_THRESHOLD:-0.55}"
CERTLH_MIN_GROUPS="${CERTLH_MIN_GROUPS:-4}"
CERTLH_MAX_GROUPS="${CERTLH_MAX_GROUPS:-8}"
CERTLH_MIN_GROUP_UNITS="${CERTLH_MIN_GROUP_UNITS:-2}"
CERTLH_MAX_GROUP_UNITS="${CERTLH_MAX_GROUP_UNITS:-8}"
CERTLH_EVENT_QUANTILE="${CERTLH_EVENT_QUANTILE:-0.80}"
CERTLH_EVENT_FLOOR="${CERTLH_EVENT_FLOOR:-0.08}"
CERTLH_GROUP_FLOOR_RATIO="${CERTLH_GROUP_FLOOR_RATIO:-0.50}"
CERTLH_BUDGET_TEMPERATURE="${CERTLH_BUDGET_TEMPERATURE:-0.25}"
CERTLH_QUERY_WEIGHT="${CERTLH_QUERY_WEIGHT:-0.35}"
CERTLH_RELAY_RATIO="${CERTLH_RELAY_RATIO:-0.10}"
CERTLH_QUERY_PEAKS_PER_ATOM="${CERTLH_QUERY_PEAKS_PER_ATOM:-2}"
CERTLH_QUERY_PEAK_QUANTILE="${CERTLH_QUERY_PEAK_QUANTILE:-0.90}"
CERTLH_QUERY_PEAK_FLOOR="${CERTLH_QUERY_PEAK_FLOOR:-0.75}"
CERTLH_QUERY_MIN_GROUP_DISTANCE="${CERTLH_QUERY_MIN_GROUP_DISTANCE:-2}"
CERTLH_CROSS_GROUP_SIMILARITY="${CERTLH_CROSS_GROUP_SIMILARITY:-0.90}"
CERTLH_CROSS_GROUP_MAX_SECONDS="${CERTLH_CROSS_GROUP_MAX_SECONDS:-8.0}"
CERTLH_DEBUG="${CERTLH_DEBUG:-False}"

CERTV4_BUDGET_MODE="${CERTV4_BUDGET_MODE:-layer_average}"
CERTV4_ATTENTION_POLICY="${CERTV4_ATTENTION_POLICY:-validated}"
CERTV4_ATTENTION_EPS="${CERTV4_ATTENTION_EPS:-0.000001}"
CERTV4_CERTIFICATE_BUDGET_RATIO="${CERTV4_CERTIFICATE_BUDGET_RATIO:-0.40}"
CERTV4_QUERY_MODE="${CERTV4_QUERY_MODE:-certificates_and_design}"
CERTV4_DESIGN_PROTECT_RATIO="${CERTV4_DESIGN_PROTECT_RATIO:-0.15}"
CERTV4_QUERY_ATOMS="${CERTV4_QUERY_ATOMS:-8}"
CERTV4_TEMPORAL_BINS="${CERTV4_TEMPORAL_BINS:-12}"
CERTV4_SPATIAL_BINS="${CERTV4_SPATIAL_BINS:-3}"
CERTV4_CANDIDATE_MULTIPLIER="${CERTV4_CANDIDATE_MULTIPLIER:-2.5}"
CERTV4_TRACK_THRESHOLD="${CERTV4_TRACK_THRESHOLD:-0.82}"
CERTV4_SPATIAL_PENALTY="${CERTV4_SPATIAL_PENALTY:-0.08}"
CERTV4_METRIC_DIM="${CERTV4_METRIC_DIM:-96}"
CERTV4_FRAME_COVERAGE_RATIO="${CERTV4_FRAME_COVERAGE_RATIO:-1.0}"
CERTV4_CELL_COVERAGE_RATIO="${CERTV4_CELL_COVERAGE_RATIO:-0.50}"
CERTV4_QUERY_THRESHOLD="${CERTV4_QUERY_THRESHOLD:-0.10}"
CERTV4_QUERY_PER_ATOM="${CERTV4_QUERY_PER_ATOM:-1}"
CERTV4_STRUCTURAL_WEIGHT="${CERTV4_STRUCTURAL_WEIGHT:-0.32}"
CERTV4_WHITENING_STRENGTH="${CERTV4_WHITENING_STRENGTH:-0.50}"
CERTV4_QUALITY_FLOOR="${CERTV4_QUALITY_FLOOR:-0.15}"
CERTV4_RIDGE="${CERTV4_RIDGE:-0.50}"
CERTV4_SWAP_STEPS="${CERTV4_SWAP_STEPS:-6}"
CERTV4_SWAP_POOL="${CERTV4_SWAP_POOL:-24}"
CERTV4_SWAP_MARGIN="${CERTV4_SWAP_MARGIN:-0.0001}"
CERTV4_FUSION_ALPHA="${CERTV4_FUSION_ALPHA:-0.12}"
CERTV4_ASSIGNMENT_TEMPERATURE="${CERTV4_ASSIGNMENT_TEMPERATURE:-0.07}"
CERTV4_DEBUG="${CERTV4_DEBUG:-False}"

CERTV5_BUDGET_MODE="${CERTV5_BUDGET_MODE:-layer_average}"
CERTV5_OT_ENABLED="${CERTV5_OT_ENABLED:-True}"
CERTV5_OT_TOPK="${CERTV5_OT_TOPK:-4}"
CERTV5_OT_TEMPERATURE="${CERTV5_OT_TEMPERATURE:-0.07}"
CERTV5_OT_STEPS="${CERTV5_OT_STEPS:-6}"
CERTV5_OT_CAPACITY_TAU="${CERTV5_OT_CAPACITY_TAU:-0.10}"
CERTV5_OT_PRIOR_SHRINK="${CERTV5_OT_PRIOR_SHRINK:-0.10}"
CERTV5_OT_LIVE_FRACTION="${CERTV5_OT_LIVE_FRACTION:-0.25}"
CERTV5_OT_COST_SLACK="${CERTV5_OT_COST_SLACK:-0.05}"
CERTV5_OT_TEMPORAL_PENALTY="${CERTV5_OT_TEMPORAL_PENALTY:-0.04}"
CERTV5_OT_MAX_DISPLACEMENT="${CERTV5_OT_MAX_DISPLACEMENT:-0.12}"
CERTV5_OT_MIN_COSINE="${CERTV5_OT_MIN_COSINE:-0.98}"
CERTV5_DEBUG="${CERTV5_DEBUG:-False}"

CERTE_BUDGET_USES_EXPANSION="${CERTE_BUDGET_USES_EXPANSION:-True}"
CERTE_RIDGE="${CERTE_RIDGE:-0.50}"
CERTE_BOTTOM_K="${CERTE_BOTTOM_K:-8}"
CERTE_SWAP_STEPS="${CERTE_SWAP_STEPS:-6}"
CERTE_REMOVE_POOL="${CERTE_REMOVE_POOL:-8}"
CERTE_ADD_POOL="${CERTE_ADD_POOL:-16}"
CERTE_VERIFY_POOL="${CERTE_VERIFY_POOL:-4}"
CERTE_SWAP_MARGIN="${CERTE_SWAP_MARGIN:-0.00001}"
CERTE_SPECTRAL_TEMPERATURE="${CERTE_SPECTRAL_TEMPERATURE:-0.05}"
CERTE_D_EFFICIENCY_FLOOR="${CERTE_D_EFFICIENCY_FLOOR:-0.995}"
CERTE_RANK_TOLERANCE="${CERTE_RANK_TOLERANCE:-0.00001}"
CERTE_DEBUG="${CERTE_DEBUG:-False}"

FAITH_TOKEN_SELECTION_METHOD="${FAITH_TOKEN_SELECTION_METHOD:-$CERTV3_TOKEN_SELECTION_METHOD}"
FAITH_BUDGET_USES_EXPANSION="${FAITH_BUDGET_USES_EXPANSION:-True}"
FAITH_MASS_STRENGTH="${FAITH_MASS_STRENGTH:-1.0}"
FAITH_VARIANCE_STRENGTH="${FAITH_VARIANCE_STRENGTH:-0.50}"
FAITH_MERGE_ALPHA="${FAITH_MERGE_ALPHA:-1.0}"
FAITH_TEMPORAL_RADIUS="${FAITH_TEMPORAL_RADIUS:-1}"
FAITH_SPATIAL_RADIUS="${FAITH_SPATIAL_RADIUS:-0.75}"
FAITH_COMPONENT_BONUS="${FAITH_COMPONENT_BONUS:-0.08}"
FAITH_TEMPORAL_PENALTY="${FAITH_TEMPORAL_PENALTY:-0.04}"
FAITH_SPATIAL_PENALTY="${FAITH_SPATIAL_PENALTY:-0.04}"
FAITH_ASSIGNMENT_TOPK="${FAITH_ASSIGNMENT_TOPK:-2}"
FAITH_ASSIGNMENT_TEMPERATURE="${FAITH_ASSIGNMENT_TEMPERATURE:-0.07}"
FAITH_MAX_LOG_BIAS="${FAITH_MAX_LOG_BIAS:-20.0}"
FAITH_ATTENTION_STRICT="${FAITH_ATTENTION_STRICT:-True}"
FAITH_DEBUG="${FAITH_DEBUG:-False}"

split_csv() {
  local text="$1"
  text="${text//,/ }"
  # shellcheck disable=SC2086
  printf '%s\n' $text
}

resolve_accelerate_launcher() {
  if command -v "$ACCELERATE" >/dev/null 2>&1; then
    ACCELERATE_LAUNCHER=("$ACCELERATE" launch)
    return
  fi
  if "$PYTHON_BIN" -c 'import accelerate' >/dev/null 2>&1; then
    ACCELERATE_LAUNCHER=("$PYTHON_BIN" -m accelerate.commands.launch)
    return
  fi
  echo "Accelerate is not installed in the active Python environment." >&2
  echo "Install it with: $PYTHON_BIN -m pip install 'accelerate>=0.29.1'" >&2
  exit 127
}

base_model_args() {
  printf 'pretrained=%s,conv_template=%s,mm_spatial_pool_mode=%s,max_frames_num=%s,attn_implementation=%s' \
    "$PRETRAINED" "$CONV_TEMPLATE" "$MM_SPATIAL_POOL_MODE" "$MAX_FRAMES_NUM" "$ATTN_IMPLEMENTATION"
}

common_compression_args() {
  local rate="$1"
  printf 'enable_flashvid=True,retention_ratio=%s,expansion=%s,do_segment=%s,segment_threshold=%s,min_segment_num=%s,complementary_segment=%s,alpha=%s,temporal_threshold=%s,pruning_layer=%s,llm_retention_ratio=%s' \
    "$rate" "$EXPANSION" "$DO_SEGMENT" "$SEGMENT_THRESHOLD" "$MIN_SEGMENT_NUM" "$COMPLEMENTARY_SEGMENT" "$ALPHA" "$TEMPORAL_THRESHOLD" "$PRUNING_LAYER" "$LLM_RETENTION_RATIO"
}

method_args() {
  local method="$1"
  case "$method" in
    flashvid)
      printf 'compression_variant=flashvid,token_selection_method=%s' "$FLASHVID_TOKEN_SELECTION_METHOD"
      ;;
    certvid)
      printf 'compression_variant=certvid,token_selection_method=%s,cert_budget_uses_expansion=%s,cert_query_atoms=%s,cert_temporal_bins=%s,cert_spatial_bins=%s,cert_candidate_multiplier=%s,cert_query_weight=%s,cert_temporal_weight=%s,cert_detail_weight=%s,cert_repair_ratio=%s,cert_fusion_alpha=%s,cert_assignment_temperature=%s,cert_track_threshold=%s,cert_spatial_penalty=%s,cert_metric_dim=%s' \
        "$CERT_TOKEN_SELECTION_METHOD" "$CERT_BUDGET_USES_EXPANSION" "$CERT_QUERY_ATOMS" "$CERT_TEMPORAL_BINS" "$CERT_SPATIAL_BINS" "$CERT_CANDIDATE_MULTIPLIER" "$CERT_QUERY_WEIGHT" "$CERT_TEMPORAL_WEIGHT" "$CERT_DETAIL_WEIGHT" "$CERT_REPAIR_RATIO" "$CERT_FUSION_ALPHA" "$CERT_ASSIGNMENT_TEMPERATURE" "$CERT_TRACK_THRESHOLD" "$CERT_SPATIAL_PENALTY" "$CERT_METRIC_DIM"
      ;;
    certvid_v2)
      printf 'compression_variant=certvid_v2,token_selection_method=%s,certv2_budget_uses_expansion=%s,certv2_query_atoms=%s,certv2_temporal_bins=%s,certv2_spatial_bins=%s,certv2_candidate_multiplier=%s,certv2_query_weight=%s,certv2_frame_floor_ratio=%s,certv2_diversity_weight=%s,certv2_coverage_weight=%s,certv2_density_neighbors=%s,certv2_track_threshold=%s,certv2_spatial_penalty=%s,certv2_metric_dim=%s,certv2_repair_ratio=%s,certv2_repair_ratio_high=%s,certv2_router_strength=%s,certv2_protect_ratio=%s,certv2_swap_margin=%s,certv2_fusion_alpha=%s,certv2_repair_fusion_alpha=%s,certv2_assignment_temperature=%s' \
        "$CERTV2_TOKEN_SELECTION_METHOD" "$CERTV2_BUDGET_USES_EXPANSION" "$CERTV2_QUERY_ATOMS" "$CERTV2_TEMPORAL_BINS" "$CERTV2_SPATIAL_BINS" "$CERTV2_CANDIDATE_MULTIPLIER" "$CERTV2_QUERY_WEIGHT" "$CERTV2_FRAME_FLOOR_RATIO" "$CERTV2_DIVERSITY_WEIGHT" "$CERTV2_COVERAGE_WEIGHT" "$CERTV2_DENSITY_NEIGHBORS" "$CERTV2_TRACK_THRESHOLD" "$CERTV2_SPATIAL_PENALTY" "$CERTV2_METRIC_DIM" "$CERTV2_REPAIR_RATIO" "$CERTV2_REPAIR_RATIO_HIGH" "$CERTV2_ROUTER_STRENGTH" "$CERTV2_PROTECT_RATIO" "$CERTV2_SWAP_MARGIN" "$CERTV2_FUSION_ALPHA" "$CERTV2_REPAIR_FUSION_ALPHA" "$CERTV2_ASSIGNMENT_TEMPERATURE"
      ;;
    certvid_v3)
      printf 'compression_variant=certvid_v3,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s' \
        "$CERTV3_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE"
      ;;
    certvid_v6)
      printf 'compression_variant=certvid_v6,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s,certv6_scene_temporal=%s,certv6_gate_enabled=%s,certv6_continuity_low=%s,certv6_continuity_high=%s,certv6_query_per_atom_max=%s' \
        "$CERTV6_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE" "$CERTV6_SCENE_TEMPORAL" "$CERTV6_GATE_ENABLED" "$CERTV6_CONTINUITY_LOW" "$CERTV6_CONTINUITY_HIGH" "$CERTV6_QUERY_PER_ATOM_MAX"
      ;;
    certvid_v7)
      printf 'compression_variant=certvid_v7,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s' \
        "$CERTV7_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE"
      printf ',certv7_min_duration_seconds=%s,certv7_transport_spatial_bins=%s,certv7_transport_epsilon=%s,certv7_transport_steps=%s,certv7_transport_spatial_weight=%s,certv7_frame_floor_ratio=%s,certv7_frame_cap_ratio=%s,certv7_budget_temperature=%s,certv7_uniqueness_weight=%s,certv7_transport_weight=%s,certv7_event_weight=%s,certv7_query_weight=%s,certv7_relay_ratio=%s,certv7_relay_query_share=%s,certv7_query_peaks_per_atom=%s,certv7_query_min_frame_gap=%s,certv7_query_peak_threshold=%s,certv7_facility_quality_mix=%s,certv7_min_reallocation_ratio=%s,certv7_d_efficiency_floor=%s,certv7_assignment_topk=%s,certv7_assignment_temperature=%s,certv7_cross_frame_cost_quantile=%s,certv7_cross_frame_similarity=%s,certv7_cross_frame_max_seconds=%s,certv7_component_bonus=%s,certv7_design_protect_ratio=%s,certv7_debug=%s' \
        "$CERTV7_MIN_DURATION_SECONDS" "$CERTV7_TRANSPORT_SPATIAL_BINS" "$CERTV7_TRANSPORT_EPSILON" "$CERTV7_TRANSPORT_STEPS" "$CERTV7_TRANSPORT_SPATIAL_WEIGHT" "$CERTV7_FRAME_FLOOR_RATIO" "$CERTV7_FRAME_CAP_RATIO" "$CERTV7_BUDGET_TEMPERATURE" "$CERTV7_UNIQUENESS_WEIGHT" "$CERTV7_TRANSPORT_WEIGHT" "$CERTV7_EVENT_WEIGHT" "$CERTV7_QUERY_WEIGHT" "$CERTV7_RELAY_RATIO" "$CERTV7_RELAY_QUERY_SHARE" "$CERTV7_QUERY_PEAKS_PER_ATOM" "$CERTV7_QUERY_MIN_FRAME_GAP" "$CERTV7_QUERY_PEAK_THRESHOLD" "$CERTV7_FACILITY_QUALITY_MIX" "$CERTV7_MIN_REALLOCATION_RATIO" "$CERTV7_D_EFFICIENCY_FLOOR" "$CERTV7_ASSIGNMENT_TOPK" "$CERTV7_ASSIGNMENT_TEMPERATURE" "$CERTV7_CROSS_FRAME_COST_QUANTILE" "$CERTV7_CROSS_FRAME_SIMILARITY" "$CERTV7_CROSS_FRAME_MAX_SECONDS" "$CERTV7_COMPONENT_BONUS" "$CERTV7_DESIGN_PROTECT_RATIO" "$CERTV7_DEBUG"
      printf ',certv7_budget_rounding=%s,certv7_v3_certificate_ratio=%s,certv7_transition_relay_share=%s,certv7_query_context_radius=%s,certv7_transition_pairs_per_boundary=%s,certv7_transition_min_similarity=%s,certv7_trajectory_min_span=%s,certv7_trajectory_points=%s,certv7_long_fusion_alpha=%s' \
        "$CERTV7_BUDGET_ROUNDING" "$CERTV7_V3_CERTIFICATE_RATIO" "$CERTV7_TRANSITION_RELAY_SHARE" "$CERTV7_QUERY_CONTEXT_RADIUS" "$CERTV7_TRANSITION_PAIRS_PER_BOUNDARY" "$CERTV7_TRANSITION_MIN_SIMILARITY" "$CERTV7_TRAJECTORY_MIN_SPAN" "$CERTV7_TRAJECTORY_POINTS" "$CERTV7_LONG_FUSION_ALPHA"
      ;;
    certvid_v8)
      printf 'compression_variant=certvid_v8,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s' \
        "$CERTV8_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE"
      printf ',certv8_enabled=%s,certv8_intent_router=%s,certv8_intent_strength=%s,certv8_min_horizon_gap_seconds=%s,certv8_min_deficit=%s,certv8_frame_floor_ratio=%s,certv8_frame_cap_ratio=%s,certv8_max_swap_ratio=%s,certv8_concentration_preserve_ratio=%s,certv8_query_peak_count=%s,certv8_query_peak_separation=%s,certv8_query_weight=%s,certv8_event_weight=%s,certv8_balance_weight=%s,certv8_design_protect_ratio=%s,certv8_query_protect_ratio=%s,certv8_d_efficiency_floor=%s,certv8_min_objective_gain=%s,certv8_cross_frame_similarity=%s,certv8_cross_frame_max_seconds=%s,certv8_stratified_enabled=%s,certv8_stratified_temporal_strength=%s,certv8_stratified_retrieval_strength=%s,certv8_stratified_generic_strength=%s,certv8_stratified_min_question_words=%s,certv8_stratified_v3_keep_ratio=%s,certv8_stratified_max_duration_seconds=%s,certv8_stratified_d_efficiency_floor=%s,certv8_stratified_query_tolerance=%s,certv8_debug=%s' \
        "$CERTV8_ENABLED" "$CERTV8_INTENT_ROUTER" "$CERTV8_INTENT_STRENGTH" "$CERTV8_MIN_HORIZON_GAP_SECONDS" "$CERTV8_MIN_DEFICIT" "$CERTV8_FRAME_FLOOR_RATIO" "$CERTV8_FRAME_CAP_RATIO" "$CERTV8_MAX_SWAP_RATIO" "$CERTV8_CONCENTRATION_PRESERVE_RATIO" "$CERTV8_QUERY_PEAK_COUNT" "$CERTV8_QUERY_PEAK_SEPARATION" "$CERTV8_QUERY_WEIGHT" "$CERTV8_EVENT_WEIGHT" "$CERTV8_BALANCE_WEIGHT" "$CERTV8_DESIGN_PROTECT_RATIO" "$CERTV8_QUERY_PROTECT_RATIO" "$CERTV8_D_EFFICIENCY_FLOOR" "$CERTV8_MIN_OBJECTIVE_GAIN" "$CERTV8_CROSS_FRAME_SIMILARITY" "$CERTV8_CROSS_FRAME_MAX_SECONDS" "$CERTV8_STRATIFIED_ENABLED" "$CERTV8_STRATIFIED_TEMPORAL_STRENGTH" "$CERTV8_STRATIFIED_RETRIEVAL_STRENGTH" "$CERTV8_STRATIFIED_GENERIC_STRENGTH" "$CERTV8_STRATIFIED_MIN_QUESTION_WORDS" "$CERTV8_STRATIFIED_V3_KEEP_RATIO" "$CERTV8_STRATIFIED_MAX_DURATION_SECONDS" "$CERTV8_STRATIFIED_D_EFFICIENCY_FLOOR" "$CERTV8_STRATIFIED_QUERY_TOLERANCE" "$CERTV8_DEBUG"
      ;;
    certvid_hr)
      printf 'compression_variant=certvid_hr,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s,certhr_horizon_gap_seconds=%s,certhr_chunk_max_seconds=%s,certhr_chunk_max_units=%s,certhr_semantic_quantile=%s,certhr_semantic_floor=%s,certhr_coverage_floor=%s,certhr_deficit_threshold=%s,certhr_query_peak_quantile=%s,certhr_query_peak_floor=%s,certhr_max_swap_ratio=%s,certhr_d_efficiency_floor=%s,certhr_add_pool=%s,certhr_remove_pool=%s,certhr_debug=%s' \
        "$CERTHR_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE" "$CERTHR_HORIZON_GAP_SECONDS" "$CERTHR_CHUNK_MAX_SECONDS" "$CERTHR_CHUNK_MAX_UNITS" "$CERTHR_SEMANTIC_QUANTILE" "$CERTHR_SEMANTIC_FLOOR" "$CERTHR_COVERAGE_FLOOR" "$CERTHR_DEFICIT_THRESHOLD" "$CERTHR_QUERY_PEAK_QUANTILE" "$CERTHR_QUERY_PEAK_FLOOR" "$CERTHR_MAX_SWAP_RATIO" "$CERTHR_D_EFFICIENCY_FLOOR" "$CERTHR_ADD_POOL" "$CERTHR_REMOVE_POOL" "$CERTHR_DEBUG"
      ;;
    certvid_lh)
      printf 'compression_variant=certvid_lh,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s,certlh_min_duration_seconds=%s,certlh_horizon_gap_seconds=%s,certlh_gate_threshold=%s,certlh_min_groups=%s,certlh_max_groups=%s,certlh_min_group_units=%s,certlh_max_group_units=%s,certlh_event_quantile=%s,certlh_event_floor=%s,certlh_group_floor_ratio=%s,certlh_budget_temperature=%s,certlh_query_weight=%s,certlh_relay_ratio=%s,certlh_query_peaks_per_atom=%s,certlh_query_peak_quantile=%s,certlh_query_peak_floor=%s,certlh_query_min_group_distance=%s,certlh_cross_group_similarity=%s,certlh_cross_group_max_seconds=%s,certlh_debug=%s' \
        "$CERTLH_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE" "$CERTLH_MIN_DURATION_SECONDS" "$CERTLH_HORIZON_GAP_SECONDS" "$CERTLH_GATE_THRESHOLD" "$CERTLH_MIN_GROUPS" "$CERTLH_MAX_GROUPS" "$CERTLH_MIN_GROUP_UNITS" "$CERTLH_MAX_GROUP_UNITS" "$CERTLH_EVENT_QUANTILE" "$CERTLH_EVENT_FLOOR" "$CERTLH_GROUP_FLOOR_RATIO" "$CERTLH_BUDGET_TEMPERATURE" "$CERTLH_QUERY_WEIGHT" "$CERTLH_RELAY_RATIO" "$CERTLH_QUERY_PEAKS_PER_ATOM" "$CERTLH_QUERY_PEAK_QUANTILE" "$CERTLH_QUERY_PEAK_FLOOR" "$CERTLH_QUERY_MIN_GROUP_DISTANCE" "$CERTLH_CROSS_GROUP_SIMILARITY" "$CERTLH_CROSS_GROUP_MAX_SECONDS" "$CERTLH_DEBUG"
      ;;
    certvid_v4)
      printf 'compression_variant=certvid_v4,token_selection_method=%s,certv4_budget_mode=%s,certv4_attention_policy=%s,certv4_attention_eps=%s,certv4_certificate_budget_ratio=%s,certv4_query_mode=%s,certv4_design_protect_ratio=%s,certv4_query_atoms=%s,certv4_temporal_bins=%s,certv4_spatial_bins=%s,certv4_candidate_multiplier=%s,certv4_track_threshold=%s,certv4_spatial_penalty=%s,certv4_metric_dim=%s,certv4_frame_coverage_ratio=%s,certv4_cell_coverage_ratio=%s,certv4_query_threshold=%s,certv4_query_per_atom=%s,certv4_structural_weight=%s,certv4_whitening_strength=%s,certv4_quality_floor=%s,certv4_ridge=%s,certv4_swap_steps=%s,certv4_swap_pool=%s,certv4_swap_margin=%s,certv4_fusion_alpha=%s,certv4_assignment_temperature=%s,certv4_debug=%s' \
        "$CERTV4_TOKEN_SELECTION_METHOD" "$CERTV4_BUDGET_MODE" "$CERTV4_ATTENTION_POLICY" "$CERTV4_ATTENTION_EPS" "$CERTV4_CERTIFICATE_BUDGET_RATIO" "$CERTV4_QUERY_MODE" "$CERTV4_DESIGN_PROTECT_RATIO" "$CERTV4_QUERY_ATOMS" "$CERTV4_TEMPORAL_BINS" "$CERTV4_SPATIAL_BINS" "$CERTV4_CANDIDATE_MULTIPLIER" "$CERTV4_TRACK_THRESHOLD" "$CERTV4_SPATIAL_PENALTY" "$CERTV4_METRIC_DIM" "$CERTV4_FRAME_COVERAGE_RATIO" "$CERTV4_CELL_COVERAGE_RATIO" "$CERTV4_QUERY_THRESHOLD" "$CERTV4_QUERY_PER_ATOM" "$CERTV4_STRUCTURAL_WEIGHT" "$CERTV4_WHITENING_STRENGTH" "$CERTV4_QUALITY_FLOOR" "$CERTV4_RIDGE" "$CERTV4_SWAP_STEPS" "$CERTV4_SWAP_POOL" "$CERTV4_SWAP_MARGIN" "$CERTV4_FUSION_ALPHA" "$CERTV4_ASSIGNMENT_TEMPERATURE" "$CERTV4_DEBUG"
      ;;
    certvid_v5)
      printf 'compression_variant=certvid_v5,token_selection_method=%s,certv3_budget_uses_expansion=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s,certv5_budget_mode=%s,certv5_ot_enabled=%s,certv5_ot_topk=%s,certv5_ot_temperature=%s,certv5_ot_steps=%s,certv5_ot_capacity_tau=%s,certv5_ot_prior_shrink=%s,certv5_ot_live_fraction=%s,certv5_ot_cost_slack=%s,certv5_ot_temporal_penalty=%s,certv5_ot_max_displacement=%s,certv5_ot_min_cosine=%s,certv5_debug=%s' \
        "$CERTV5_TOKEN_SELECTION_METHOD" "$CERTV3_BUDGET_USES_EXPANSION" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE" "$CERTV5_BUDGET_MODE" "$CERTV5_OT_ENABLED" "$CERTV5_OT_TOPK" "$CERTV5_OT_TEMPERATURE" "$CERTV5_OT_STEPS" "$CERTV5_OT_CAPACITY_TAU" "$CERTV5_OT_PRIOR_SHRINK" "$CERTV5_OT_LIVE_FRACTION" "$CERTV5_OT_COST_SLACK" "$CERTV5_OT_TEMPORAL_PENALTY" "$CERTV5_OT_MAX_DISPLACEMENT" "$CERTV5_OT_MIN_COSINE" "$CERTV5_DEBUG"
      ;;
    certvid_e)
      printf 'compression_variant=certvid_e,token_selection_method=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s,certe_budget_uses_expansion=%s,certe_ridge=%s,certe_bottom_k=%s,certe_swap_steps=%s,certe_remove_pool=%s,certe_add_pool=%s,certe_verify_pool=%s,certe_swap_margin=%s,certe_spectral_temperature=%s,certe_d_efficiency_floor=%s,certe_rank_tolerance=%s,certe_debug=%s' \
        "$CERTE_TOKEN_SELECTION_METHOD" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE" "$CERTE_BUDGET_USES_EXPANSION" "$CERTE_RIDGE" "$CERTE_BOTTOM_K" "$CERTE_SWAP_STEPS" "$CERTE_REMOVE_POOL" "$CERTE_ADD_POOL" "$CERTE_VERIFY_POOL" "$CERTE_SWAP_MARGIN" "$CERTE_SPECTRAL_TEMPERATURE" "$CERTE_D_EFFICIENCY_FLOOR" "$CERTE_RANK_TOLERANCE" "$CERTE_DEBUG"
      ;;
    faithvid)
      printf 'compression_variant=faithvid,token_selection_method=%s,certv3_query_atoms=%s,certv3_temporal_bins=%s,certv3_spatial_bins=%s,certv3_candidate_multiplier=%s,certv3_query_weight=%s,certv3_track_threshold=%s,certv3_spatial_penalty=%s,certv3_metric_dim=%s,certv3_frame_coverage_ratio=%s,certv3_cell_coverage_ratio=%s,certv3_query_threshold=%s,certv3_query_per_atom=%s,certv3_structural_weight=%s,certv3_whitening_strength=%s,certv3_quality_floor=%s,certv3_ridge=%s,certv3_swap_steps=%s,certv3_swap_pool=%s,certv3_swap_margin=%s,certv3_fusion_alpha=%s,certv3_assignment_temperature=%s,faith_budget_uses_expansion=%s,faith_mass_strength=%s,faith_variance_strength=%s,faith_merge_alpha=%s,faith_temporal_radius=%s,faith_spatial_radius=%s,faith_component_bonus=%s,faith_temporal_penalty=%s,faith_spatial_penalty=%s,faith_assignment_topk=%s,faith_assignment_temperature=%s,faith_max_log_bias=%s,faith_attention_strict=%s,faith_debug=%s' \
        "$FAITH_TOKEN_SELECTION_METHOD" "$CERTV3_QUERY_ATOMS" "$CERTV3_TEMPORAL_BINS" "$CERTV3_SPATIAL_BINS" "$CERTV3_CANDIDATE_MULTIPLIER" "$CERTV3_QUERY_WEIGHT" "$CERTV3_TRACK_THRESHOLD" "$CERTV3_SPATIAL_PENALTY" "$CERTV3_METRIC_DIM" "$CERTV3_FRAME_COVERAGE_RATIO" "$CERTV3_CELL_COVERAGE_RATIO" "$CERTV3_QUERY_THRESHOLD" "$CERTV3_QUERY_PER_ATOM" "$CERTV3_STRUCTURAL_WEIGHT" "$CERTV3_WHITENING_STRENGTH" "$CERTV3_QUALITY_FLOOR" "$CERTV3_RIDGE" "$CERTV3_SWAP_STEPS" "$CERTV3_SWAP_POOL" "$CERTV3_SWAP_MARGIN" "$CERTV3_FUSION_ALPHA" "$CERTV3_ASSIGNMENT_TEMPERATURE" "$FAITH_BUDGET_USES_EXPANSION" "$FAITH_MASS_STRENGTH" "$FAITH_VARIANCE_STRENGTH" "$FAITH_MERGE_ALPHA" "$FAITH_TEMPORAL_RADIUS" "$FAITH_SPATIAL_RADIUS" "$FAITH_COMPONENT_BONUS" "$FAITH_TEMPORAL_PENALTY" "$FAITH_SPATIAL_PENALTY" "$FAITH_ASSIGNMENT_TOPK" "$FAITH_ASSIGNMENT_TEMPERATURE" "$FAITH_MAX_LOG_BIAS" "$FAITH_ATTENTION_STRICT" "$FAITH_DEBUG"
      ;;
    *)
      echo "Unsupported LLaVA-OneVision method: $method" >&2
      return 1
      ;;
  esac
}

mkdir -p "$OUTPUT_PATH"
resolve_accelerate_launcher

for method in $(split_csv "$METHODS"); do
  for rate in $(split_csv "$RATES"); do
    model_args="$(base_model_args),$(common_compression_args "$rate"),$(method_args "$method")"
    for task in $(split_csv "$TASKS"); do
      run_output="$OUTPUT_PATH/${method}_r${rate}_${task}"
      cmd=(
        "${ACCELERATE_LAUNCHER[@]}"
        --main_process_port "$MAIN_PROCESS_PORT"
        --num_processes "$NUM_PROCESSES"
        -m lmms_eval
        --model llava_onevision
        --model_args "$model_args"
        --tasks "$task"
        --batch_size "$BATCH_SIZE"
        --output_path "$run_output"
      )
      if [[ -n "$LIMIT" ]]; then
        cmd+=(--limit "$LIMIT")
      fi
      if [[ "$LOG_SAMPLES" == "1" ]]; then
        cmd+=(--log_samples --log_samples_suffix "llava_onevision_${method}_r${rate}")
      fi

      printf '[lmms-eval] method=%s rate=%s task=%s\n' "$method" "$rate" "$task"
      printf '[lmms-eval]'; printf ' %q' "${cmd[@]}"; printf '\n'
      if [[ "$method" == "certvid_v8" ]]; then
        diagnostics_path="${CERTV8_DIAGNOSTICS_JSONL:-$run_output/certvid_v8_diagnostics.jsonl}"
        printf '[certvid-v8] diagnostics=%s detail=%s\n' \
          "$diagnostics_path" "$CERTV8_DIAGNOSTICS_DETAIL"
        env \
          CERTV8_DIAGNOSTICS_JSONL="$diagnostics_path" \
          CERTV8_DIAGNOSTICS_DETAIL="$CERTV8_DIAGNOSTICS_DETAIL" \
          "${cmd[@]}"
      elif [[ "$method" == "flashvid" ]]; then
        diagnostics_path="${FLASHVID_DIAGNOSTICS_JSONL:-$run_output/flashvid_diagnostics.jsonl}"
        printf '[flashvid] diagnostics=%s detail=%s\n' \
          "$diagnostics_path" "$FLASHVID_DIAGNOSTICS_DETAIL"
        env \
          FLASHVID_DIAGNOSTICS_JSONL="$diagnostics_path" \
          FLASHVID_DIAGNOSTICS_DETAIL="$FLASHVID_DIAGNOSTICS_DETAIL" \
          "${cmd[@]}"
      else
        "${cmd[@]}"
      fi
    done
  done
done
