#!/bin/bash

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

# Evaluation benchmarks.
TASKS=("videomme" "egoschema" "mvbench" "longvideobench_val_v" "mlvu_test")

# Pretrained model path.
PRETRAINED="Qwen/Qwen2.5-VL-7B-Instruct"

# ! FlashVid arguments.
RETENTION_RATIOS=(0.10 0.15 0.20 0.25)
## Dyseg (fixed)
DO_SEGMENT=True
MIN_SEGMENT_NUM=4
COMPLEMENTARY_SEGMENT=True
## ADTS and TSTM (fixed)
TOKEN_SELECTION_METHOD=attn_div # * Use ADTSv1 for Qwen2.5-VL
ALPHA=0.70
TEMPORAL_THRESHOLD=0.8
## Graph-ST ablation switches (default keeps original FlashVID path)
COMPRESSION_VARIANT=${COMPRESSION_VARIANT:-flashvid} # flashvid | graph
QUESTION_AWARE_REWEIGHTING=${QUESTION_AWARE_REWEIGHTING:-False}
ADAPTIVE_TOKEN_BUDGET=${ADAPTIVE_TOKEN_BUDGET:-False}
ADAPTIVE_BUDGET_LOW=${ADAPTIVE_BUDGET_LOW:-0.10}
ADAPTIVE_BUDGET_MID=${ADAPTIVE_BUDGET_MID:-0.15}
ADAPTIVE_BUDGET_HIGH=${ADAPTIVE_BUDGET_HIGH:-0.20}
GRAPH_TOPK=${GRAPH_TOPK:-4}
GRAPH_TEMPORAL_RADIUS=${GRAPH_TEMPORAL_RADIUS:-1}
MEMORY_TOKEN_RATIO=${MEMORY_TOKEN_RATIO:-0.10}
CERTV3_BUDGET_USES_EXPANSION=${CERTV3_BUDGET_USES_EXPANSION:-True}
CERTV3_QUERY_ATOMS=${CERTV3_QUERY_ATOMS:-8}
CERTV3_TEMPORAL_BINS=${CERTV3_TEMPORAL_BINS:-12}
CERTV3_SPATIAL_BINS=${CERTV3_SPATIAL_BINS:-3}
CERTV3_CANDIDATE_MULTIPLIER=${CERTV3_CANDIDATE_MULTIPLIER:-2.5}
CERTV3_QUERY_WEIGHT=${CERTV3_QUERY_WEIGHT:-0.18}
CERTV3_TRACK_THRESHOLD=${CERTV3_TRACK_THRESHOLD:-0.82}
CERTV3_SPATIAL_PENALTY=${CERTV3_SPATIAL_PENALTY:-0.08}
CERTV3_METRIC_DIM=${CERTV3_METRIC_DIM:-96}
CERTV3_FRAME_COVERAGE_RATIO=${CERTV3_FRAME_COVERAGE_RATIO:-1.0}
CERTV3_CELL_COVERAGE_RATIO=${CERTV3_CELL_COVERAGE_RATIO:-0.50}
CERTV3_QUERY_THRESHOLD=${CERTV3_QUERY_THRESHOLD:-0.10}
CERTV3_QUERY_PER_ATOM=${CERTV3_QUERY_PER_ATOM:-1}
CERTV3_STRUCTURAL_WEIGHT=${CERTV3_STRUCTURAL_WEIGHT:-0.32}
CERTV3_WHITENING_STRENGTH=${CERTV3_WHITENING_STRENGTH:-0.50}
CERTV3_QUALITY_FLOOR=${CERTV3_QUALITY_FLOOR:-0.15}
CERTV3_RIDGE=${CERTV3_RIDGE:-0.50}
CERTV3_SWAP_STEPS=${CERTV3_SWAP_STEPS:-6}
CERTV3_SWAP_POOL=${CERTV3_SWAP_POOL:-24}
CERTV3_SWAP_MARGIN=${CERTV3_SWAP_MARGIN:-0.0001}
CERTV3_FUSION_ALPHA=${CERTV3_FUSION_ALPHA:-0.12}
CERTV3_ASSIGNMENT_TEMPERATURE=${CERTV3_ASSIGNMENT_TEMPERATURE:-0.07}
FAITH_BUDGET_USES_EXPANSION=${FAITH_BUDGET_USES_EXPANSION:-True}
FAITH_MASS_STRENGTH=${FAITH_MASS_STRENGTH:-1.0}
FAITH_VARIANCE_STRENGTH=${FAITH_VARIANCE_STRENGTH:-0.50}
FAITH_MERGE_ALPHA=${FAITH_MERGE_ALPHA:-1.0}
FAITH_TEMPORAL_RADIUS=${FAITH_TEMPORAL_RADIUS:-1}
FAITH_SPATIAL_RADIUS=${FAITH_SPATIAL_RADIUS:-0.75}
FAITH_COMPONENT_BONUS=${FAITH_COMPONENT_BONUS:-0.08}
FAITH_TEMPORAL_PENALTY=${FAITH_TEMPORAL_PENALTY:-0.04}
FAITH_SPATIAL_PENALTY=${FAITH_SPATIAL_PENALTY:-0.04}
FAITH_ASSIGNMENT_TOPK=${FAITH_ASSIGNMENT_TOPK:-2}
FAITH_ASSIGNMENT_TEMPERATURE=${FAITH_ASSIGNMENT_TEMPERATURE:-0.07}
FAITH_MAX_LOG_BIAS=${FAITH_MAX_LOG_BIAS:-20.0}
FAITH_ATTENTION_STRICT=${FAITH_ATTENTION_STRICT:-True}
FAITH_DEBUG=${FAITH_DEBUG:-False}
if [ "$ADAPTIVE_TOKEN_BUDGET" = "True" ]; then
    # retention_ratio is selected dynamically from {adaptive_budget_low, mid, high}
    RETENTION_RATIOS=(0.15)
fi
## Inner-LLM Pruning (fixed)
EXPANSION=1.25
PRUNING_LAYER=20
LLM_RETENTION_RATIO=0.3

BASE_FLASHVID_ARGS="enable_flashvid=True,expansion=$EXPANSION,do_segment=$DO_SEGMENT,min_segment_num=$MIN_SEGMENT_NUM,complementary_segment=$COMPLEMENTARY_SEGMENT,token_selection_method=$TOKEN_SELECTION_METHOD,alpha=$ALPHA,temporal_threshold=$TEMPORAL_THRESHOLD,compression_variant=$COMPRESSION_VARIANT,question_aware_reweighting=$QUESTION_AWARE_REWEIGHTING,adaptive_token_budget=$ADAPTIVE_TOKEN_BUDGET,adaptive_budget_low=$ADAPTIVE_BUDGET_LOW,adaptive_budget_mid=$ADAPTIVE_BUDGET_MID,adaptive_budget_high=$ADAPTIVE_BUDGET_HIGH,graph_topk=$GRAPH_TOPK,graph_temporal_radius=$GRAPH_TEMPORAL_RADIUS,memory_token_ratio=$MEMORY_TOKEN_RATIO,certv3_budget_uses_expansion=$CERTV3_BUDGET_USES_EXPANSION,certv3_query_atoms=$CERTV3_QUERY_ATOMS,certv3_temporal_bins=$CERTV3_TEMPORAL_BINS,certv3_spatial_bins=$CERTV3_SPATIAL_BINS,certv3_candidate_multiplier=$CERTV3_CANDIDATE_MULTIPLIER,certv3_query_weight=$CERTV3_QUERY_WEIGHT,certv3_track_threshold=$CERTV3_TRACK_THRESHOLD,certv3_spatial_penalty=$CERTV3_SPATIAL_PENALTY,certv3_metric_dim=$CERTV3_METRIC_DIM,certv3_frame_coverage_ratio=$CERTV3_FRAME_COVERAGE_RATIO,certv3_cell_coverage_ratio=$CERTV3_CELL_COVERAGE_RATIO,certv3_query_threshold=$CERTV3_QUERY_THRESHOLD,certv3_query_per_atom=$CERTV3_QUERY_PER_ATOM,certv3_structural_weight=$CERTV3_STRUCTURAL_WEIGHT,certv3_whitening_strength=$CERTV3_WHITENING_STRENGTH,certv3_quality_floor=$CERTV3_QUALITY_FLOOR,certv3_ridge=$CERTV3_RIDGE,certv3_swap_steps=$CERTV3_SWAP_STEPS,certv3_swap_pool=$CERTV3_SWAP_POOL,certv3_swap_margin=$CERTV3_SWAP_MARGIN,certv3_fusion_alpha=$CERTV3_FUSION_ALPHA,certv3_assignment_temperature=$CERTV3_ASSIGNMENT_TEMPERATURE,faith_budget_uses_expansion=$FAITH_BUDGET_USES_EXPANSION,faith_mass_strength=$FAITH_MASS_STRENGTH,faith_variance_strength=$FAITH_VARIANCE_STRENGTH,faith_merge_alpha=$FAITH_MERGE_ALPHA,faith_temporal_radius=$FAITH_TEMPORAL_RADIUS,faith_spatial_radius=$FAITH_SPATIAL_RADIUS,faith_component_bonus=$FAITH_COMPONENT_BONUS,faith_temporal_penalty=$FAITH_TEMPORAL_PENALTY,faith_spatial_penalty=$FAITH_SPATIAL_PENALTY,faith_assignment_topk=$FAITH_ASSIGNMENT_TOPK,faith_assignment_temperature=$FAITH_ASSIGNMENT_TEMPERATURE,faith_max_log_bias=$FAITH_MAX_LOG_BIAS,faith_attention_strict=$FAITH_ATTENTION_STRICT,faith_debug=$FAITH_DEBUG,pruning_layer=$PRUNING_LAYER,llm_retention_ratio=$LLM_RETENTION_RATIO"

# Model arguments.
MAX_NUM_FRAMES=32
# * Configurable pixel constraints.
# MIN_PIXELS=50716 # 64*28*28
# MAX_PIXELS=200704 # 256*28*28
ATTN_IMPLEMENTATION=flash_attention_2
# BASE_MODEL_ARGS="pretrained=$PRETRAINED,max_num_frames=$MAX_NUM_FRAMES,max_pixels=$MAX_PIXELS,min_pixels=$MIN_PIXELS,attn_implementation=$ATTN_IMPLEMENTATION"
BASE_MODEL_ARGS="pretrained=$PRETRAINED,max_num_frames=$MAX_NUM_FRAMES,attn_implementation=$ATTN_IMPLEMENTATION"


for retention_ratio in "${RETENTION_RATIOS[@]}"; do
    echo "Running with retention_ratio=${retention_ratio}"
    MODEL_ARGS="$BASE_MODEL_ARGS,$BASE_FLASHVID_ARGS,retention_ratio=${retention_ratio}"
    for task in "${TASKS[@]}"; do
        echo "Evaluating task: $task"
        accelerate launch \
        --main_process_port 18888 \
        --num_processes 8 \
        -m lmms_eval \
        --model qwen2_5_vl \
        --model_args $MODEL_ARGS \
        --tasks $task \
        --batch_size 1 \
        --log_samples \
        --log_samples_suffix "qwen2_5_vl" \
        --output_path ./logs/flashvid
    done
    echo "Finished running with retention_ratio=${retention_ratio}"
done
