from typing import Optional

from dataclasses import dataclass, field


@dataclass
class FlashVidConfig:
    # Average retention ratio.
    retention_ratio: float = field(default=0.25)

    # 1) Token Selection Method. Defaults to ADTS.
    alpha: float = field(default=0.7) # Ratio of ADTS tokens.
    token_selection_method: str = field(default="attn_div")

    # 2) Tree-based Spatio-Temporal Token Merging.
    temporal_threshold: float = field(default=0.8)
    dynamic_temporal_threshold: bool = field(default=False)
    temporal_threshold_quantile: float = field(default=0.8)
    temporal_threshold_min: float = field(default=0.0)
    temporal_threshold_max: float = field(default=0.99)
    last_dynamic_temporal_threshold: Optional[float] = field(default=None)
    temporal_match_mode: str = field(default="global")  # global | local
    temporal_local_radius: int = field(default=2)
    temporal_hysteresis: float = field(default=0.0)
    min_keep_per_frame: int = field(default=0)
    temporal_merge_mode: str = field(default="tree")  # tree | graph
    graph_temporal_topk: int = field(default=3)
    graph_temporal_radius: int = field(default=1)
    graph_temporal_skip: int = field(default=1)
    graph_merge_protect_ratio: float = field(default=0.15)
    graph_merge_target_ratio: float = field(default=0.65)
    graph_merge_representative: str = field(default="medoid")  # medoid | mean
    graph_final_tokens_per_frame: int = field(default=0)
    graph_final_frame_floor_ratio: float = field(default=0.55)
    graph_skip_spatial_merge_when_capped: bool = field(default=True)

    # FastGraphVID: ATS salient branch + GraphSTM residual medoids.
    fastgraph_ats_ratio: float = field(default=0.60)
    fastgraph_budget_uses_expansion: bool = field(default=True)
    fastgraph_temporal_radius: int = field(default=1)
    fastgraph_temporal_skip: int = field(default=1)
    fastgraph_temporal_topk: int = field(default=2)
    fastgraph_edge_threshold: float = field(default=0.0)
    fastgraph_protect_ratio: float = field(default=0.15)
    fastgraph_attn_weight: float = field(default=0.55)
    fastgraph_novelty_weight: float = field(default=0.30)
    fastgraph_density_weight: float = field(default=0.15)

    # ApexVID: adaptive evidence/event/memory compression.
    apex_evidence_ratio: float = field(default=0.45)
    apex_event_ratio: float = field(default=0.30)
    apex_memory_ratio: float = field(default=0.25)
    apex_router_strength: float = field(default=0.50)
    apex_summary_temperature: float = field(default=0.07)
    apex_frame_floor_ratio: float = field(default=0.35)
    apex_question_weight: float = field(default=0.20)

    # CertVID: constrained evidence coreset with shared DeepStack fusion.
    cert_budget_uses_expansion: bool = field(default=True)
    cert_query_atoms: int = field(default=6)
    cert_temporal_bins: int = field(default=8)
    cert_spatial_bins: int = field(default=3)
    cert_candidate_multiplier: float = field(default=3.0)
    cert_query_weight: float = field(default=0.20)
    cert_temporal_weight: float = field(default=0.20)
    cert_detail_weight: float = field(default=0.10)
    cert_repair_ratio: float = field(default=0.20)
    cert_fusion_alpha: float = field(default=0.25)
    cert_assignment_temperature: float = field(default=0.07)
    cert_track_threshold: float = field(default=0.82)
    cert_spatial_penalty: float = field(default=0.08)
    cert_metric_dim: int = field(default=256)

    # CertVID V2: evidence backbone with gated trajectory repair.
    certv2_budget_uses_expansion: bool = field(default=True)
    certv2_query_atoms: int = field(default=6)
    certv2_temporal_bins: int = field(default=8)
    certv2_spatial_bins: int = field(default=3)
    certv2_candidate_multiplier: float = field(default=3.0)
    certv2_query_weight: float = field(default=0.18)
    certv2_frame_floor_ratio: float = field(default=0.08)
    certv2_diversity_weight: float = field(default=0.12)
    certv2_coverage_weight: float = field(default=0.10)
    certv2_density_neighbors: int = field(default=4)
    certv2_track_threshold: float = field(default=0.82)
    certv2_spatial_penalty: float = field(default=0.08)
    certv2_metric_dim: int = field(default=256)
    certv2_repair_ratio: float = field(default=0.05)
    certv2_repair_ratio_high: float = field(default=0.13)
    certv2_router_strength: float = field(default=0.65)
    certv2_protect_ratio: float = field(default=0.30)
    certv2_swap_margin: float = field(default=0.02)
    certv2_fusion_alpha: float = field(default=0.25)
    certv2_repair_fusion_alpha: float = field(default=0.08)
    certv2_assignment_temperature: float = field(default=0.07)

    # CertVID V3: certified regularized D-optimal evidence design.
    certv3_budget_uses_expansion: bool = field(default=True)
    certv3_query_atoms: int = field(default=8)
    certv3_temporal_bins: int = field(default=12)
    certv3_spatial_bins: int = field(default=3)
    certv3_candidate_multiplier: float = field(default=2.5)
    certv3_query_weight: float = field(default=0.18)
    certv3_track_threshold: float = field(default=0.82)
    certv3_spatial_penalty: float = field(default=0.08)
    certv3_metric_dim: int = field(default=96)
    certv3_frame_coverage_ratio: float = field(default=1.0)
    certv3_cell_coverage_ratio: float = field(default=0.50)
    certv3_query_threshold: float = field(default=0.10)
    certv3_query_per_atom: int = field(default=1)
    certv3_structural_weight: float = field(default=0.32)
    certv3_whitening_strength: float = field(default=0.50)
    certv3_quality_floor: float = field(default=0.15)
    certv3_ridge: float = field(default=0.50)
    certv3_swap_steps: int = field(default=6)
    certv3_swap_pool: int = field(default=24)
    certv3_swap_margin: float = field(default=1e-4)
    certv3_fusion_alpha: float = field(default=0.12)
    certv3_assignment_temperature: float = field(default=0.07)

    # CertVID V6: V3 design with scene-aware temporal structure and gating.
    certv6_scene_temporal: bool = field(default=True)
    certv6_gate_enabled: bool = field(default=True)
    certv6_continuity_low: float = field(default=0.55)
    certv6_continuity_high: float = field(default=0.80)
    certv6_query_per_atom_max: int = field(default=3)

    # CertVID V7: long-horizon relation evidence with exact short-video V3 fallback.
    certv7_min_duration_seconds: float = field(default=120.0)
    certv7_transport_spatial_bins: int = field(default=4)
    certv7_transport_epsilon: float = field(default=0.08)
    certv7_transport_steps: int = field(default=8)
    certv7_transport_spatial_weight: float = field(default=0.20)
    certv7_frame_floor_ratio: float = field(default=1.0)
    certv7_frame_cap_ratio: float = field(default=1.0)
    certv7_budget_temperature: float = field(default=0.50)
    certv7_uniqueness_weight: float = field(default=0.25)
    certv7_transport_weight: float = field(default=0.35)
    certv7_event_weight: float = field(default=0.20)
    certv7_query_weight: float = field(default=0.20)
    certv7_budget_rounding: str = field(default="per_frame_ceil")
    certv7_v3_certificate_ratio: float = field(default=0.05)
    certv7_relay_ratio: float = field(default=0.25)
    certv7_relay_query_share: float = field(default=0.25)
    certv7_transition_relay_share: float = field(default=0.45)
    certv7_query_peaks_per_atom: int = field(default=2)
    certv7_query_min_frame_gap: int = field(default=3)
    certv7_query_peak_threshold: float = field(default=0.70)
    certv7_query_context_radius: int = field(default=1)
    certv7_transition_pairs_per_boundary: int = field(default=2)
    certv7_transition_min_similarity: float = field(default=0.30)
    certv7_trajectory_min_span: int = field(default=3)
    certv7_trajectory_points: int = field(default=3)
    certv7_facility_quality_mix: float = field(default=0.18)
    certv7_min_reallocation_ratio: float = field(default=0.02)
    certv7_d_efficiency_floor: float = field(default=0.80)
    certv7_assignment_topk: int = field(default=2)
    certv7_assignment_temperature: float = field(default=0.07)
    certv7_cross_frame_cost_quantile: float = field(default=0.45)
    certv7_cross_frame_similarity: float = field(default=0.82)
    certv7_cross_frame_max_seconds: float = field(default=12.0)
    certv7_component_bonus: float = field(default=0.08)
    certv7_design_protect_ratio: float = field(default=0.15)
    certv7_long_fusion_alpha: float = field(default=0.04)
    certv7_debug: bool = field(default=False)

    # CertVID V8: V3-preserving long-context evidence repair.
    certv8_enabled: bool = field(default=True)
    certv8_intent_router: bool = field(default=True)
    certv8_intent_strength: float = field(default=0.75)
    certv8_min_horizon_gap_seconds: float = field(default=4.0)
    certv8_min_deficit: float = field(default=0.04)
    certv8_frame_floor_ratio: float = field(default=0.45)
    certv8_frame_cap_ratio: float = field(default=2.00)
    certv8_max_swap_ratio: float = field(default=0.30)
    certv8_query_peak_count: int = field(default=2)
    certv8_query_peak_separation: int = field(default=2)
    certv8_query_weight: float = field(default=0.30)
    certv8_event_weight: float = field(default=0.25)
    certv8_balance_weight: float = field(default=0.30)
    certv8_design_protect_ratio: float = field(default=0.08)
    certv8_query_protect_ratio: float = field(default=0.05)
    certv8_d_efficiency_floor: float = field(default=0.95)
    certv8_min_objective_gain: float = field(default=0.001)
    certv8_cross_frame_similarity: float = field(default=0.88)
    certv8_cross_frame_max_seconds: float = field(default=8.0)
    certv8_debug: bool = field(default=False)

    # CertVID-HR: V3-preserving long-horizon evidence repair.
    certhr_horizon_gap_seconds: float = field(default=4.0)
    certhr_chunk_max_seconds: float = field(default=60.0)
    certhr_chunk_max_units: int = field(default=4)
    certhr_semantic_quantile: float = field(default=0.85)
    certhr_semantic_floor: float = field(default=0.10)
    certhr_coverage_floor: float = field(default=0.70)
    certhr_deficit_threshold: float = field(default=0.05)
    certhr_query_peak_quantile: float = field(default=0.90)
    certhr_query_peak_floor: float = field(default=0.75)
    certhr_max_swap_ratio: float = field(default=0.05)
    certhr_d_efficiency_floor: float = field(default=0.995)
    certhr_add_pool: int = field(default=32)
    certhr_remove_pool: int = field(default=24)
    certhr_debug: bool = field(default=False)

    # CertVID-LH: long-horizon temporal allocation and evidence-chain relays.
    certlh_min_duration_seconds: float = field(default=120.0)
    certlh_horizon_gap_seconds: float = field(default=4.0)
    certlh_gate_threshold: float = field(default=0.55)
    certlh_min_groups: int = field(default=4)
    certlh_max_groups: int = field(default=8)
    certlh_min_group_units: int = field(default=2)
    certlh_max_group_units: int = field(default=8)
    certlh_event_quantile: float = field(default=0.80)
    certlh_event_floor: float = field(default=0.08)
    certlh_group_floor_ratio: float = field(default=0.50)
    certlh_budget_temperature: float = field(default=0.25)
    certlh_query_weight: float = field(default=0.35)
    certlh_relay_ratio: float = field(default=0.10)
    certlh_query_peaks_per_atom: int = field(default=2)
    certlh_query_peak_quantile: float = field(default=0.90)
    certlh_query_peak_floor: float = field(default=0.75)
    certlh_query_min_group_distance: int = field(default=2)
    certlh_cross_group_similarity: float = field(default=0.90)
    certlh_cross_group_max_seconds: float = field(default=8.0)
    certlh_debug: bool = field(default=False)

    # CertVID V4: verifiable budget-constrained D-optimal evidence design.
    certv4_budget_mode: str = field(default="layer_average")
    certv4_attention_policy: str = field(default="validated")
    certv4_attention_eps: float = field(default=1e-6)
    certv4_certificate_budget_ratio: float = field(default=0.40)
    certv4_query_mode: str = field(default="certificates_and_design")
    certv4_design_protect_ratio: float = field(default=0.15)
    certv4_query_atoms: int = field(default=8)
    certv4_temporal_bins: int = field(default=12)
    certv4_spatial_bins: int = field(default=3)
    certv4_candidate_multiplier: float = field(default=2.5)
    certv4_track_threshold: float = field(default=0.82)
    certv4_spatial_penalty: float = field(default=0.08)
    certv4_metric_dim: int = field(default=96)
    certv4_frame_coverage_ratio: float = field(default=1.0)
    certv4_cell_coverage_ratio: float = field(default=0.50)
    certv4_query_threshold: float = field(default=0.10)
    certv4_query_per_atom: int = field(default=1)
    certv4_structural_weight: float = field(default=0.32)
    certv4_whitening_strength: float = field(default=0.50)
    certv4_quality_floor: float = field(default=0.15)
    certv4_ridge: float = field(default=0.50)
    certv4_swap_steps: int = field(default=6)
    certv4_swap_pool: int = field(default=24)
    certv4_swap_margin: float = field(default=1e-4)
    certv4_fusion_alpha: float = field(default=0.12)
    certv4_assignment_temperature: float = field(default=0.07)
    certv4_debug: bool = field(default=False)
    certv4_num_hidden_layers: int = field(default=0)
    certv4_inner_hook_enabled: bool = field(default=False)

    # CertVID V5: exact V3 anchors with residual-recovery transport.
    certv5_budget_mode: str = field(default="layer_average")
    certv5_ot_enabled: bool = field(default=True)
    certv5_ot_topk: int = field(default=4)
    certv5_ot_temperature: float = field(default=0.07)
    certv5_ot_steps: int = field(default=6)
    certv5_ot_capacity_tau: float = field(default=0.10)
    certv5_ot_prior_shrink: float = field(default=0.10)
    certv5_ot_live_fraction: float = field(default=0.25)
    certv5_ot_cost_slack: float = field(default=0.05)
    certv5_ot_temporal_penalty: float = field(default=0.04)
    certv5_ot_max_displacement: float = field(default=0.12)
    certv5_ot_min_cosine: float = field(default=0.98)
    certv5_debug: bool = field(default=False)
    certv5_num_hidden_layers: int = field(default=0)
    certv5_inner_hook_enabled: bool = field(default=False)

    # CertVID-E: V3 evidence design with D-efficient E-optimal exchanges.
    certe_budget_uses_expansion: bool = field(default=True)
    certe_ridge: float = field(default=0.50)
    certe_bottom_k: int = field(default=8)
    certe_swap_steps: int = field(default=6)
    certe_remove_pool: int = field(default=8)
    certe_add_pool: int = field(default=16)
    certe_verify_pool: int = field(default=4)
    certe_swap_margin: float = field(default=1e-5)
    certe_spectral_temperature: float = field(default=0.05)
    certe_d_efficiency_floor: float = field(default=0.995)
    certe_rank_tolerance: float = field(default=1e-5)
    certe_debug: bool = field(default=False)

    # FaithVID: functionally faithful merging with mass-corrected attention.
    faith_budget_uses_expansion: bool = field(default=True)
    faith_mass_strength: float = field(default=1.0)
    faith_variance_strength: float = field(default=0.50)
    faith_merge_alpha: float = field(default=1.0)
    faith_temporal_radius: int = field(default=1)
    faith_spatial_radius: float = field(default=0.75)
    faith_component_bonus: float = field(default=0.08)
    faith_temporal_penalty: float = field(default=0.04)
    faith_spatial_penalty: float = field(default=0.04)
    faith_assignment_topk: int = field(default=2)
    faith_assignment_temperature: float = field(default=0.07)
    faith_max_log_bias: float = field(default=20.0)
    faith_attention_strict: bool = field(default=True)
    faith_debug: bool = field(default=False)

    # Dynamic Video Segmentation (DySeg).
    do_segment: bool = field(default=True)
    segment_threshold: float = field(default=0.9)
    min_segment_num: int = field(default=8)
    complementary_segment: bool = field(default=True)

    # Vision-Side Compression params.
    num_attn_div_tokens: Optional[int] = field(default=None)
    num_sttm_tokens: Optional[int] = field(default=None)

    # Inner-LLM Compression params.
    visual_token_start_index: Optional[int] = field(default=None)
    visual_token_length: Optional[int] = field(default=None)
    vision_token_length: Optional[int] = field(default=None)
    llm_token_length: Optional[int] = field(default=None)
    expansion: float = field(default=1.25)
    pruning_layer: int = field(default=20)
    llm_retention_ratio: float = field(default=0.3)

    # Experimental compression variant.
    # "flashvid": original ADTS + TSTM path.
    # "talon": transport-aligned low-rank + sparse innovation path.
    # "certvid_e": V3-compatible D-efficient E-optimal evidence design.
    # "certvid_lh": V3-preserving long-horizon allocation and relay path.
    # "certvid_v7": long-horizon relation evidence and balanced local coverage.
    # "certvid_v8": V3-preserving temporal and query-evidence repair.
    # "faithvid": mass-corrected functionally faithful merging path.
    # "prismvid": Qwen3 DeepStack-aware exact coreset path.
    compression_variant: str = field(default="flashvid")

    # Question-aware token reweighting.
    question_aware_reweighting: bool = field(default=False)
    question_reweight_beta: float = field(default=0.35)

    # TALON compression.
    talon_transport_radius: int = field(default=1)
    talon_rank_ratio: float = field(default=0.40)
    talon_rank_min: int = field(default=2)
    talon_rank_max: int = field(default=32)
    talon_budget_scale: float = field(default=0.60)
    talon_target_tokens_per_frame: int = field(default=0)
    talon_short_target_tokens_per_frame: int = field(default=0)
    talon_medium_target_tokens_per_frame: int = field(default=0)
    talon_long_target_tokens_per_frame: int = field(default=0)
    talon_min_total_tokens: int = field(default=1)
    talon_fast_rank_plan: bool = field(default=True)
    talon_background_max_ratio: float = field(default=0.45)
    talon_frame_balanced_selection: bool = field(default=True)
    talon_basis_method: str = field(default="randomized")  # covariance | randomized
    talon_basis_oversample: int = field(default=4)
    talon_innovation_attention_weight: float = field(default=0.45)
    talon_motion_importance_weight: float = field(default=0.35)
    talon_boundary_importance_weight: float = field(default=0.10)
    talon_question_frame_weight: float = field(default=0.20)
    talon_frame_balanced_memory: bool = field(default=True)
    talon_memory_mode: str = field(default="raw")  # raw | merge
    talon_anchor_safety_ratio: float = field(default=0.28)
    talon_anchor_diversity_weight: float = field(default=0.0)
    talon_anchor_candidate_multiplier: float = field(default=4.0)
    talon_spatial_anchor_coverage: bool = field(default=False)
    talon_spatial_anchor_ratio: float = field(default=0.35)
    talon_spatial_anchor_rows: int = field(default=3)
    talon_spatial_anchor_cols: int = field(default=3)
    talon_spatial_anchor_score: str = field(default="fused")
    talon_spatial_anchor_apply_to_short: bool = field(default=False)
    talon_frame_coverage_floor_ratio: float = field(default=0.65)
    talon_frame_importance_pooling: str = field(default="mean")
    talon_frame_importance_topk: int = field(default=6)
    talon_frame_importance_apply_to_short: bool = field(default=False)
    talon_medium_frame_coverage_floor_ratio: float = field(default=-1.0)
    talon_long_frame_coverage_floor_ratio: float = field(default=-1.0)
    talon_frame_local_budget_ratio: float = field(default=1.0)
    talon_question_recall_ratio: float = field(default=0.06)
    talon_question_recall_qweight: float = field(default=0.65)
    talon_persistence_recall_ratio: float = field(default=0.0)
    talon_persistence_recall_qweight: float = field(default=0.50)
    talon_persistence_recall_pweight: float = field(default=0.35)
    talon_persistence_apply_to_short: bool = field(default=False)
    talon_persistence_apply_to_medium: bool = field(default=True)
    talon_persistence_apply_to_long: bool = field(default=False)
    talon_object_evidence_ratio: float = field(default=0.0)
    talon_object_evidence_qweight: float = field(default=0.35)
    talon_object_evidence_sweight: float = field(default=0.45)
    talon_object_evidence_pweight: float = field(default=0.10)
    talon_object_evidence_apply_to_short: bool = field(default=False)
    talon_object_evidence_apply_to_medium: bool = field(default=True)
    talon_object_evidence_apply_to_long: bool = field(default=False)
    talon_question_pooling: str = field(default="mean")
    talon_question_pooling_topk: int = field(default=4)
    talon_question_contrast_weight: float = field(default=0.0)
    talon_question_contrast_apply_to_short: bool = field(default=False)
    talon_monotonic_base_tokens_per_frame: int = field(default=20)
    talon_budget_strategy: str = field(default="marginal")  # ratio | marginal
    talon_budget_mode: str = field(default="uniform")  # uniform | attention
    talon_transport_mode: str = field(default="hard")  # hard | soft
    talon_transport_temperature: float = field(default=0.07)
    talon_lite_enabled: bool = field(default=False)
    talon_echo_temperature: float = field(default=0.07)
    talon_echo_topk_neighbors: int = field(default=4)
    talon_echo_residual_weight: float = field(default=0.0)
    talon_echo_score_mode: str = field(default="mse")  # mse | cosine
    talon_rd_spectral_weight: float = field(default=1.0)
    talon_rd_innovation_weight: float = field(default=1.0)
    talon_use_question_innovation: bool = field(default=True)
    talon_innovation_qweight: float = field(default=0.25)
    talon_output_mode: str = field(default="manifold")  # manifold | coefficient
    talon_reconstruction_blend: float = field(default=0.0)
    talon_anchor_score_weight: float = field(default=0.35)
    talon_min_anchor_per_frame: int = field(default=2)
    talon_passthrough_ratio: float = field(default=0.15)
    talon_passthrough_min: int = field(default=2)
    talon_use_segmentation: bool = field(default=True)
    talon_disable_oversegmentation: bool = field(default=True)
    talon_max_segments: int = field(default=4)
    talon_deepstack_mode: str = field(default="keep")  # disable | keep | auto

    # Residual memory tokens.
    memory_token_ratio: float = field(default=0.10)
    memory_token_min: int = field(default=1)
    memory_token_max: int = field(default=16)

    # Adaptive token budget.
    adaptive_token_budget: bool = field(default=False)
    adaptive_budget_low: float = field(default=0.10)
    adaptive_budget_mid: float = field(default=0.15)
    adaptive_budget_high: float = field(default=0.20)
    last_adaptive_retention_ratio: Optional[float] = field(default=None)
    talon_adaptive_target_low: int = field(default=0)
    talon_adaptive_target_mid: int = field(default=0)
    talon_adaptive_target_high: int = field(default=0)
    talon_complexity_floor: float = field(default=0.20)
    talon_complexity_ceil: float = field(default=0.40)
    talon_adaptive_gamma: float = field(default=1.0)
    talon_adaptive_target_enabled: bool = field(default=False)
    talon_force_fixed_target: bool = field(default=False)
    talon_target_mean_cap: float = field(default=0.0)
    talon_running_target_sum: float = field(default=0.0)
    talon_running_target_count: int = field(default=0)
    talon_unified_selection: bool = field(default=False)
    talon_low_budget_mode_threshold: int = field(default=20)
    talon_low_budget_rank_cap: int = field(default=0)
    talon_background_global_ratio: float = field(default=0.60)
    talon_event_budget_ratio: float = field(default=0.30)
    talon_memory_fused_weight: float = field(default=0.50)
    talon_memory_residual_weight: float = field(default=0.35)
    talon_memory_frame_weight: float = field(default=0.15)
    talon_recall_memory_mode: str = field(default="raw")
    talon_final_fused_weight: float = field(default=0.70)
    talon_final_residual_weight: float = field(default=0.20)
    talon_final_frame_weight: float = field(default=0.10)
    talon_anchor_keep_bonus: float = field(default=0.10)
    talon_recall_keep_bonus: float = field(default=0.08)
    talon_event_keep_bonus: float = field(default=0.04)
    talon_legacy_base_keep_ratio: float = field(default=0.85)
    talon_prior_candidate_ratio: float = field(default=0.12)
    talon_prior_keep_bonus: float = field(default=0.06)
    talon_flash_prior_channel_ratio: float = field(default=0.12)
    talon_flash_prior_channel_method: str = field(default="attn_div_v2")
    talon_flash_prior_channel_min_per_frame: int = field(default=1)
    talon_flash_prior_channel_max_per_frame: int = field(default=4)
    talon_flash_prior_channel_bonus: float = field(default=0.06)
    talon_final_anchor_min_ratio: float = field(default=0.24)
    talon_final_recall_min_ratio: float = field(default=0.10)
    talon_force_anchor_recall_quota: bool = field(default=True)
    talon_global_topk_ratio: float = field(default=0.70)
    talon_rescue_enabled: bool = field(default=True)
    talon_rescue_ratio: float = field(default=0.08)
    talon_rescue_from_memory_only: bool = field(default=True)
    talon_rescue_fused_weight: float = field(default=0.55)
    talon_rescue_residual_weight: float = field(default=0.35)
    talon_rescue_frame_weight: float = field(default=0.10)
    talon_rescue_global_ratio: float = field(default=0.85)
    talon_rerank_with_flash_prior: bool = field(default=True)
    talon_flash_prior_ratio: float = field(default=0.20)
    talon_recall_semantic_ratio: float = field(default=0.50)
    talon_recall_event_ratio: float = field(default=0.25)
    talon_recall_frame_ratio: float = field(default=0.15)
    talon_recall_global_ratio: float = field(default=0.55)
    talon_duration_aware: bool = field(default=False)
    talon_medium_anchor_safety_ratio: float = field(default=0.72)
    talon_medium_event_budget_ratio: float = field(default=0.30)
    talon_medium_global_topk_ratio: float = field(default=0.70)
    talon_long_anchor_safety_ratio: float = field(default=0.80)
    talon_long_event_budget_ratio: float = field(default=0.14)
    talon_long_global_topk_ratio: float = field(default=0.85)
    talon_task_aware_event: bool = field(default=False)
    talon_task_event_attention_weight: float = field(default=0.82)
    talon_task_event_qweight: float = field(default=0.30)
    talon_visual_task_balance: bool = field(default=False)
    talon_visual_task_anchor_ratio: float = field(default=0.84)
    talon_visual_task_event_ratio: float = field(default=0.12)
    talon_visual_task_recall_ratio: float = field(default=0.02)
    talon_knowledge_visual_anchor_ratio: float = field(default=0.78)
    talon_knowledge_visual_event_ratio: float = field(default=0.18)
    talon_knowledge_visual_recall_ratio: float = field(default=0.06)
    talon_adaptive_router: bool = field(default=False)
    talon_router_apply_to_short: bool = field(default=False)
    talon_router_visual_anchor_ratio: float = field(default=0.76)
    talon_router_visual_event_ratio: float = field(default=0.24)
    talon_router_visual_recall_ratio: float = field(default=0.06)
    talon_router_temporal_anchor_ratio: float = field(default=0.66)
    talon_router_temporal_event_ratio: float = field(default=0.34)
    talon_router_temporal_recall_ratio: float = field(default=0.08)
    talon_router_balanced_anchor_ratio: float = field(default=0.72)
    talon_router_balanced_event_ratio: float = field(default=0.30)
    talon_router_balanced_recall_ratio: float = field(default=0.08)
    talon_router_visual_concentration_threshold: float = field(default=0.28)
    talon_router_low_residual_threshold: float = field(default=0.30)
    talon_router_temporal_entropy_threshold: float = field(default=0.95)
    talon_router_temporal_residual_threshold: float = field(default=0.36)
    talon_temporal_chunk_aware: bool = field(default=False)
    talon_temporal_num_chunks: int = field(default=4)
    talon_temporal_chunk_min_ratio: float = field(default=0.18)
    talon_temporal_chunk_score: str = field(default="combined")
    talon_track_aware: bool = field(default=False)
    talon_track_budget_ratio: float = field(default=0.12)
    talon_track_tokens_per_slot: int = field(default=1)
    talon_track_score: str = field(default="combined")
    talon_absorb_dropped_tokens: bool = field(default=False)
    talon_absorb_ratio: float = field(default=0.35)
    talon_absorb_alpha: float = field(default=0.25)
    talon_absorb_score: str = field(default="combined")
    talon_summary_replacement: bool = field(default=False)
    talon_summary_raw_swap: bool = field(default=False)
    talon_summary_ratio: float = field(default=0.08)
    talon_summary_num_chunks: int = field(default=8)
    talon_summary_pool_topk: int = field(default=12)
    talon_summary_alpha: float = field(default=0.55)
    talon_summary_score: str = field(default="combined")
    current_video_duration: Optional[str] = field(default=None)
    current_task_category: Optional[str] = field(default=None)
    current_category: Optional[str] = field(default=None)
    last_talon_target_tokens_per_frame: Optional[int] = field(default=None)
    last_talon_complexity_score: Optional[float] = field(default=None)
    last_talon_target_budget: Optional[int] = field(default=None)
    last_talon_anchor_tokens: Optional[int] = field(default=None)
    last_talon_rank_tokens: Optional[int] = field(default=None)
    last_talon_event_tokens: Optional[int] = field(default=None)
    last_talon_recall_tokens: Optional[int] = field(default=None)
    last_talon_persistence_tokens: Optional[int] = field(default=None)
    last_talon_object_tokens: Optional[int] = field(default=None)
    last_talon_memory_tokens: Optional[int] = field(default=None)
    last_talon_segment_count: Optional[int] = field(default=None)
    last_talon_rank_cap: Optional[int] = field(default=None)
    last_talon_chosen_rank: Optional[int] = field(default=None)
    last_talon_duplicate_index_count: Optional[int] = field(default=None)
    last_talon_question_aware_active: Optional[bool] = field(default=None)
    last_talon_router_mode_code: Optional[int] = field(default=None)
    last_talon_router_fused_concentration: Optional[float] = field(default=None)
    last_talon_router_residual_concentration: Optional[float] = field(default=None)
    last_talon_router_question_concentration: Optional[float] = field(default=None)
    last_talon_router_frame_entropy: Optional[float] = field(default=None)
    # Spatial grid metadata (set by model hooks when available).
    H: Optional[int] = field(default=None)
    W: Optional[int] = field(default=None)

    # Decode-stage policy scaffold (Route3 hook, default no-op).
    decode_policy: str = field(default="none")
    decode_kv_budget_ratio: float = field(default=1.0)
    decode_update_interval: int = field(default=4)
    decode_start_layer: int = field(default=0)

    # PrismVID fields are appended to preserve positional construction.
    prism_budget_uses_expansion: bool = field(default=True)
    prism_metric_dim: int = field(default=256)
    prism_query_atoms: int = field(default=6)
    prism_candidate_multiplier: float = field(default=2.25)
    prism_probe_tokens: int = field(default=512)
    prism_frame_floor_ratio: float = field(default=0.20)
    prism_attention_weight: float = field(default=0.30)
    prism_event_weight: float = field(default=0.24)
    prism_query_weight: float = field(default=0.16)
    prism_disagreement_weight: float = field(default=0.16)
    prism_router_strength: float = field(default=0.50)
    prism_coverage_weight: float = field(default=0.68)
    prism_pareto_weight: float = field(default=0.20)
    prism_batch_size: int = field(default=8)
